import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:bharat_flow/core/utils/language_helper.dart';
import 'package:bharat_flow/core/providers/location_provider.dart';


enum UserRole { farmer, trader, customer }

class AppSettings {
  final UserRole role;
  final String language;
  final bool priceAlerts;
  final bool mandiUpdates;
  final bool pinEnabled;
  final String pinCode;
  final bool autoLanguage;
  final bool weatherNotifications;
  final DateTime? lastSync;

  AppSettings({
    required this.role,
    required this.language,
    required this.priceAlerts,
    required this.mandiUpdates,
    this.pinEnabled = false,
    this.pinCode = '',
    this.autoLanguage = false,
    this.weatherNotifications = true,
    this.lastSync,
  });

  AppSettings copyWith({
    UserRole? role,
    String? language,
    bool? priceAlerts,
    bool? mandiUpdates,
    bool? pinEnabled,
    String? pinCode,
    bool? autoLanguage,
    bool? weatherNotifications,
    DateTime? lastSync,
  }) {
    return AppSettings(
      role: role ?? this.role,
      language: language ?? this.language,
      priceAlerts: priceAlerts ?? this.priceAlerts,
      mandiUpdates: mandiUpdates ?? this.mandiUpdates,
      pinEnabled: pinEnabled ?? this.pinEnabled,
      pinCode: pinCode ?? this.pinCode,
      autoLanguage: autoLanguage ?? this.autoLanguage,
      weatherNotifications: weatherNotifications ?? this.weatherNotifications,
      lastSync: lastSync ?? this.lastSync,
    );
  }
}

class SettingsNotifier extends StateNotifier<AppSettings> {
  final _box = Hive.box('settings');

  SettingsNotifier() : super(AppSettings(
    role: UserRole.farmer,
    language: 'English',
    priceAlerts: true,
    mandiUpdates: true,
    autoLanguage: false,
    weatherNotifications: true,
  )) {
    _loadSettings();
  }

  void _loadSettings() {
    final roleIndex = _box.get('role', defaultValue: 0);
    final language = _box.get('language', defaultValue: 'English');
    final priceAlerts = _box.get('price_alerts', defaultValue: true);
    final mandiUpdates = _box.get('mandi_updates', defaultValue: true);
    final pinEnabled = _box.get('pin_enabled', defaultValue: false);
    final pinCode = _box.get('pin_code', defaultValue: '');
    final autoLanguage = _box.get('auto_language_enabled', defaultValue: false);
    final weatherNotifications = _box.get('weather_notifications_enabled', defaultValue: true);
    final lastSyncStr = _box.get('mandi_last_sync');
    final lastSync = lastSyncStr != null ? DateTime.tryParse(lastSyncStr.toString()) : null;

    state = AppSettings(
      role: UserRole.values[roleIndex],
      language: language,
      priceAlerts: priceAlerts,
      mandiUpdates: mandiUpdates,
      pinEnabled: pinEnabled,
      pinCode: pinCode,
      autoLanguage: autoLanguage,
      weatherNotifications: weatherNotifications,
      lastSync: lastSync,
    );
  }

  Future<void> updateLastSync(DateTime time) async {
    state = state.copyWith(lastSync: time);
    await _box.put('mandi_last_sync', time.toIso8601String());
  }

  Future<void> setRole(UserRole role) async {
    state = state.copyWith(role: role);
    await _box.put('role', role.index);
  }

  Future<void> setLanguage(String lang) async {
    state = state.copyWith(language: lang);
    await _box.put('language', lang);
  }

  Future<void> togglePriceAlerts(bool value) async {
    state = state.copyWith(priceAlerts: value);
    await _box.put('price_alerts', value);
  }

  Future<void> toggleMandiUpdates(bool value) async {
    state = state.copyWith(mandiUpdates: value);
    await _box.put('mandi_updates', value);
  }

  Future<void> togglePinSecurity(bool value) async {
    state = state.copyWith(pinEnabled: value);
    await _box.put('pin_enabled', value);
  }

  Future<void> setPinCode(String code) async {
    state = state.copyWith(pinCode: code);
    await _box.put('pin_code', code);
  }

  Future<void> toggleAutoLanguage(bool value) async {
    state = state.copyWith(autoLanguage: value);
    await _box.put('auto_language_enabled', value);
  }

  Future<void> toggleWeatherNotifications(bool value) async {
    state = state.copyWith(weatherNotifications: value);
    await _box.put('weather_notifications_enabled', value);
  }
}


final settingsProvider = StateNotifierProvider<SettingsNotifier, AppSettings>((ref) {
  return SettingsNotifier();
});

// Translation Map for core UI
final translationsProvider = Provider<Map<String, String>>((ref) {

  final settings = ref.watch(settingsProvider);
  String lang = settings.language;

  if (settings.autoLanguage) {
    final location = ref.watch(locationProvider);
    final autoLangCode = LanguageHelper.getLanguageForLocation(location.state, location.city);
    
    final codeToName = {
      'hi': 'Hindi', 'gu': 'Gujarati', 'pa': 'Punjabi', 'mr': 'Marathi',
      'bn': 'Bengali', 'te': 'Telugu', 'ta': 'Tamil', 'kn': 'Kannada', 'ml': 'Malayalam'
    };
    lang = codeToName[autoLangCode] ?? 'English';
  }
  
  final Map<String, Map<String, String>> data = {

    'Hindi': {
      'welcome': 'स्वागत है,',
      'farmer': 'किसान',
      'trader': 'व्यापारी',
      'mandi': 'मंडी',
      'product': 'फसल',
      'news': 'खबरें',
      'khata': 'डिजिटल खाता',
      'store': 'भारत ब्रांड स्टोर',
      'search_hint': 'मंडी खोजें...',
      'closest_mandi': 'नजदीकी मंडी',
      'account': 'खाता',
      'language': 'भाषा',
      'mandi_intelligence': 'मंडी इंटेलिजेंस',
      'mandis': 'मंडियां',
      'products': 'फसलें',
      'search_products': 'फसल खोजें...',
      'home': 'होम',
      'favorites': 'पसंदीदा',
      'soil': 'मिट्टी',
      'logistics': 'लॉजिस्टिक्स',
      'route': 'रास्ता',
      'subsidy': 'सब्सिडी',
      'reports': 'रिपोर्ट',
      'festival': 'त्यौहार',
      'ai_price': 'AI भाव',
      'analytics': 'एनालिटिक्स',
      'trends': 'ट्रेंड्स',
      'govt_buy': 'सरकारी खरीद',
      'offline': 'ऑफलाइन',
      'compare': 'तुलना',
      'voice': 'आवाज',
      'mandi_tools': 'मंडी और खेती के उपकरण',
      'items': 'सामान',
      'trend_up': 'बढ़त',
      'trend_down': 'गिरावट',
      'bharat_munafa_advisor': 'भारत मुनाफा एडवाइजर',
      'sell': 'मैं बेचना चाहता हूँ',
      'buy': 'मैं खरीदना चाहता हूँ',
      'qty_unit': 'मात्रा इकाई',
      'search_mandi': 'मंडी खोजें',
      'source_buy': 'स्रोत (यहाँ से खरीदें)',
      'target_source': 'लक्ष्य (स्रोत)',
      'select_product': 'फसल चुनें',
      'cost_qty_data': 'लागत और मात्रा डेटा',
      'buy_cost': 'खरीद लागत',
      'budget': 'बजट',
      'transport': 'परिवहन',
      'extra_cost': 'अतिरिक्त लागत',
      'comm_percent': 'कमीशन (%)',
      'labor_per_q': 'मजदूरी / क्विंटल',
      'sell_analysis': 'बिक्री विश्लेषण',
      'buy_analysis': 'खरीद विश्लेषण',
      'total_cost': 'कुल लागत',
      'total_expenses': 'कुल खर्च',
      'required_fund': 'आवश्यक फंड',
      'save_analysis': 'विश्लेषण सहेजें',
      'analysis_saved': 'विश्लेषण सहेजा गया!',
      'ok': 'ठीक है',
      'explore_all_items': 'सभी सामान देखें',
      'top_movers': 'आज के टॉप मूवर्स',
      'high_demand': 'अधिक मांग',
      'all_products': 'सभी फसलें',
      'distance': 'दूरी',
      'timings': 'समय',
      'phone': 'फ़ोन',
      'call': 'कॉल करें',
      'directions': 'रास्ता देखें',
      'variety_grade': 'किस्म और ग्रेड',
      'price_per_qtl': 'कीमत (प्रति क्विंटल)',
      'grade': 'ग्रेड',
      'range': 'सीमा',
      'home': 'होम',
      'favorites': 'पसंदीदा',
      'store': 'स्टोर',
      'profile': 'प्रोफ़ाइल',
      'mandi_tools': 'मंडी और खेती के उपकरण',
      'fetching': 'खोज रहे हैं...',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'personal_info': 'व्यक्तिगत जानकारी',
      'language_location': 'भाषा और स्थान',
      'auto_language': 'स्वचालित भाषा',
      'price_alerts': 'मूल्य अलर्ट',
      'mandi_updates': 'मंडी अपडेट',
      'security': 'सुरक्षा',
      'change_pin': 'पिन बदलें',
      'support': 'सहायता',
      'net_balance': 'कुल शेष',
      'total_sales': 'कुल बिक्री',
      'total_expenses': 'कुल खर्च',
      'search_transactions': 'लेनदेन खोजें...',
      'all_transactions': 'सभी लेनदेन',
      'recent_activity': 'हाल की गतिविधि',
      'add_transaction': 'लेनदेन जोड़ें',
      'title': 'शीर्षक',
      'amount': 'राशि',
      'credit': 'जमा',
      'debit': 'निकासी',
      'save_transaction': 'लेनदेन सहेजें',
      'member_since': 'सदस्यता:',
      'joined_today': 'आज ही जुड़े हैं',
      'days_ago': 'दिन पहले',
      'days': 'दिन',
      'weather_impact': 'मौसम का प्रभाव',
      'local_forecast_caps': 'स्थानीय पूर्वानुमान',
      'no_notifications': 'कोई नई सूचना नहीं है',
      'crop_vulnerability_caps': 'फसल संवेदनशीलता (आपके पसंदीदा)',
      'no_fav_products_advice': 'अभी तक कोई पसंदीदा फसल नहीं जोड़ी गई है।\nमंडी इंटेलिजेंस में जाकर कुछ जोड़ें!',
      'rainfall_probability_caps': 'बारिश की संभावना',
      'expert_advisory_caps': 'विशेषज्ञ सलाह',
      'loading_advice': 'सलाह लोड हो रही है...',
      'advice_unavailable': 'सलाह उपलब्ध नहीं है',
      'nearby_safe_storage_caps': 'पास के सुरक्षित भंडारण',
      'govt_warehouse_a1': 'सरकारी गोदाम A1',
      '2.4_km_away': '2.4 किमी दूर',
      'available_space': 'उपलब्ध स्थान',
      'mandi_tools': 'मंडी और खेती के उपकरण',
      'home': 'होम',
      'favorites': 'पसंदीदा',
      'what_sown_short': 'आपके खेत में क्या बोया है?',
      'nearest_mandi': 'सबसे पास की मंडी',
      'no_products_found': 'आस-पास कोई फसल नहीं मिली',
      'done': 'हो गया',
      'favorites_alerts': 'पसंदीदा और अलर्ट',
      'favorite_commodities': 'पसंदीदा फसलें',
      'no_favorites_yet': 'अभी तक कोई पसंदीदा नहीं',
      'add_mandis_track': 'आसानी से ट्रैक करने के लिए मंडियाँ जोड़ें',
      'active_price_alerts': 'सक्रिय मूल्य अलर्ट',
      'favorite': 'पसंदीदा',
      'edit_caps': 'बदलें',
      'done_caps': 'हो गया',
      'skip': 'छोड़ें',
      'search_products': 'खोजें...',
      'price_targets_met': 'मूल्य लक्ष्य पूरे हुए',
      'no_alerts_set': 'अभी कोई अलर्ट नहीं है',
      'target': 'लक्ष्य',
      'hit': 'मिल गया',
      'stable': 'स्थिर',
      'set_new_alert': 'नया अलर्ट सेट करें',
      'set_price_alert': 'मूल्य अलर्ट सेट करें',
      'alert_me_when': 'अलर्ट करें जब मूल्य हो:',
      'target_price': 'लक्ष्य मूल्य',
      'save_alert': 'अलर्ट सुरक्षित करें',
      'above': 'ऊपर',
      'below': 'नीचे',
      'current_price': 'वर्तमान मूल्य',
      'live_caps': 'लाइव',
      'stable_caps': 'स्थिर',
      'live_price_caps': 'लाइव मूल्य',
      'hit': 'लक्ष्य मिला',
      'price_targets_met': 'मूल्य लक्ष्य मिले',
      'reached_desired_price': 'आपकी लक्षित कीमत तक पहुँच गया है।',
      'favorite_commodities': 'पसंदीदा फसलें',
      'active_price_alerts': 'सक्रिय मूल्य अलर्ट',
      'insight_for_you': 'आपके लिए जानकारी',
      'volatile_insight_desc': 'सभी मंडियों में सर्वोत्तम मूल्य पर खरीदने के लिए अलर्ट सेट करें।',
      'top_price': 'उच्चतम भाव',
      'low_price': 'न्यूनतम भाव',
      'get_directions': 'रास्ता देखें',
      'updated': 'अपडेट किया गया',
      'recently': 'अभी हाल ही में',
      'var': 'किस्म',
      'grd': 'ग्रेड',
      'net_profit': 'कुल मुनाफा',
      'net_saving': 'कुल बचत',
      'ai_sell_opp': 'AI: बेचने का सबसे अच्छा अवसर',
      'ai_buy_opp': 'AI: खरीदने का सबसे अच्छा अवसर',
      'buy_price_caps': 'खरीद मूल्य',
      'sell_price_caps': 'बिक्री मूल्य',
      'your_budget_caps': 'आपका बजट',
      'mandi_price_caps': 'मंडी भाव',
      'expense_breakdown': 'खर्चों का विवरण',
      'commission': 'कमीशन',
      'labor_loading': 'मजदूरी (लोडिंग)',
      'freight': 'भाड़ा',
      'extra': 'अतिरिक्त',
      'sale': 'बिक्री',
      'cost': 'लागत',
      'exp': 'खर्च',
      'data_source': 'डेटा स्रोत: DATA.GOV.IN',
      'grains': 'अनाज',
      'vegetables': 'सब्जियाँ',
      'fruits': 'फल',
      'spices': 'मसाले',
      'pulses': 'दालें',
      'oilseeds': 'तिलहन',
      'fibers': 'फाइबर',
      'plantation': 'बागवानी',
      'flowers': 'फूल',
      'others': 'अन्य',
      'categories': 'श्रेणियाँ',
      'fetching_location': 'स्थान खोज रहे हैं...',
      'search_bharat_products': 'भारत उत्पाद खोजें...',
      'all': 'सभी',
      'fertilizer': 'खाद',
      'seeds': 'बीज',
      'atta': 'आटा',
      'dal': 'दाल',
      'in_stock': 'स्टॉक में',
      'govt_certified': 'सरकारी प्रमाणित',
      'add_to_cart': 'कार्ट में जोड़ें',
      'no_products_available': 'कोई उत्पाद उपलब्ध नहीं है',
      'lowest_price_first': 'न्यूनतम भाव पहले',
      'highest_price_first': 'अधिकतम भाव पहले',
      'no_mandi_reports': 'इस उत्पाद के लिए कोई मंडी रिपोर्ट नहीं है।',
      'map': 'नक्शा',
      'system_initializing': 'सीस्टम चालू हो रही है...',
      'connecting_to_bharat_network': 'भारत नेटवर्क के साथ जुड़ाव...',
      'finding_farm_location': 'आपके खेत का स्थान खोज रहे हैं...',
      'location_found': 'स्थान मिल गया।',
      'welcome_exclamation': 'स्वागत है!',
      'preparing_crops': 'फसलें तैयार कर रहे हैं...',
      'ready_exclamation': 'तैयार है!',
      'bharat_flow_ready': 'भारतफ्लो तैयार है।',
      'mandi_loaded': 'मंडियाँ लोड हो गई...',
      'empowered_kisan_bharat': 'सशक्त किसान · सशक्त भारत',
      'live_price': 'लाइव भाव: ',
      'alert_me_when_price': 'मुझे सूचित करें जब भाव:',
      'quintal': 'क्विंटल',
      'soil_health': 'मिट्टी की सेहत',
      'bhai_have_card': 'भाई, क्या आपके पास सॉइल हेल्थ कार्ड है?',
      'scan_report': 'हाँ, रिपोर्ट स्कैन करें',
      'find_lab': 'नहीं, नज़दीकी लैब ढूँढें',
      'how_to_sample': 'मिट्टी का सैंपल कैसे लें?',
      'nearby_labs': 'नज़दीकी लैब',
      'previous_reports': 'पुरानी रिपोर्ट्स',
      'national_level': 'राष्ट्रीय स्तर',
      'state_level': 'राज्य स्तर',
      'online': 'ऑनलाइन',
      'km_away': 'किमी दूर',
      'step1': 'खेत से 8-10 जगह से मिट्टी लें।',
      'step2': '6 इंच गहरा "V" आकार का गड्ढा खोदें।',
      'step3': 'घास और कचरा साफ करें।',
      'step4': 'सबको मिलाकर 500 ग्राम मिट्टी लैब भेजें।',
      'buyer_tab': 'खरीददार (Buyer)',
      'seller_tab': 'विक्रेता (Seller)',
    },
    'Gujarati': {
      'welcome': 'સ્વાગત છે,',
      'farmer': 'ખેડૂત',
      'trader': 'વેપારી',
      'mandi': 'મંડી',
      'product': 'પાક',
      'news': 'સમાચાર',
      'khata': 'ડિજિટલ ખાતા',
      'store': 'ભારત બ્રાન્ડ સ્ટોર',
      'search_hint': 'મંડી શોધો...',
      'closest_mandi': 'નજીકની મંડી',
      'account': 'ખાતું',
      'language': 'ભાષા',
      'mandi_intelligence': 'મંડી ઇન્ટેલિજન્સ',
      'mandis': 'મંડીઓ',
      'products': 'પાક',
      'search_products': 'પાક શોધો...',
      'home': 'હોમ',
      'favorites': 'પસંદગી',
      'soil': 'જમીન',
      'logistics': 'લોજિસ્ટિક્સ',
      'route': 'રસ્તો',
      'subsidy': 'સબસિડી',
      'reports': 'રિપોર્ટ',
      'festival': 'તહેવાર',
      'ai_price': 'AI ભાવ',
      'analytics': 'એનાલિટિક્સ',
      'trends': 'ટ્રેન્ડ્સ',
      'govt_buy': 'સરકારી ખરીદી',
      'offline': 'ઓફલાઇન',
      'compare': 'તુલના',
      'voice': 'અવાજ',
      'mandi_tools': 'મંડી અને ખેતીના સાધનો',
      'items': 'વસ્તુઓ',
      'trend_up': 'વધારો',
      'trend_down': 'ઘટાડો',
      'bharat_munafa_advisor': 'ભારત મુનાફા એડવાઈઝર',
      'sell': 'મારે વેચવું છે',
      'buy': 'મારે ખરીદવું છે',
      'qty_unit': 'જથ્થાનો એકમ',
      'search_mandi': 'મંડી શોધો',
      'source_buy': 'સ્ત્રોત (અહીંથી ખરીદો)',
      'target_source': 'લક્ષ્ય (સ્ત્રોત)',
      'select_product': 'પાક પસંદ કરો',
      'cost_qty_data': 'ખર્ચ અને જથ્થાનો ડેટા',
      'buy_cost': 'ખરીદ કિંમત',
      'budget': 'બજેટ',
      'transport': 'પરિવહન',
      'extra_cost': 'વધારાનો ખર્ચ',
      'comm_percent': 'કમિશન (%)',
      'labor_per_q': 'મજૂરી / ક્વિન્ટલ',
      'sell_analysis': 'વેચાણ વિશ્લેષણ',
      'buy_analysis': 'ખરીદી વિશ્લેષણ',
      'total_cost': 'કુલ કિંમત',
      'total_expenses': 'કુલ ખર્ચ',
      'required_fund': 'જરૂરી ફંડ',
      'save_analysis': 'વિશ્લેષણ સાચવો',
      'analysis_saved': 'વિશ્લેષણ સાચવવામાં આવ્યું!',
      'ok': 'બરાબર',
      'explore_all_items': 'બધી વસ્તુઓ જુઓ',
      'top_movers': 'આજના ટોચના મૂવર્સ',
      'high_demand': 'વધારે માંગ',
      'all_products': 'બધા પાક',
      'distance': 'અંતર',
      'timings': 'સમય',
      'phone': 'ફોન',
      'call': 'કૉલ કરો',
      'directions': 'દિશાઓ',
      'variety_grade': 'જાત અને ગ્રેડ',
      'price_per_qtl': 'કિંમત (પ્રતિ ક્વિન્ટલ)',
      'grade': 'ગ્રેડ',
      'range': 'રેન્જ',
      'home': 'હોમ',
      'favorites': 'પસંદગીના',
      'store': 'સ્ટોર',
      'profile': 'પ્રોફાઇલ',
      'mandi_tools': 'મંડી અને ખેતીના સાધનો',
      'fetching': 'મેળવી રહ્યા છીએ...',
      'settings': 'સેટિંગ્સ',
      'logout': 'લોગઆઉટ',
      'personal_info': 'વ્યક્તિગત માહિતી',
      'language_location': 'ભાષા અને સ્થાન',
      'auto_language': 'ઓટો લેંગ્વેજ',
      'price_alerts': 'કિંમત એલર્ટ',
      'mandi_updates': 'મંડી અપડેટ્સ',
      'security': 'સુરક્ષા',
      'change_pin': 'પિન બદલો',
      'support': 'સપોર્ટ',
      'net_balance': 'કુલ બેલેન્સ',
      'total_sales': 'કુલ વેચાણ',
      'total_expenses': 'કુલ ખર્ચ',
      'search_transactions': 'લેવડ-દેવડ શોધો...',
      'all_transactions': 'બધી લેવડ-દેવડ',
      'recent_activity': 'તાજેતરની પ્રવૃત્તિ',
      'add_transaction': 'ટ્રાન્ઝેક્શન ઉમેરો',
      'title': 'શીર્ષક',
      'amount': 'રકમ',
      'credit': 'જમા',
      'debit': 'ઉધાર',
      'save_transaction': 'ટ્રાન્ઝેક્શન સાચવો',
      'member_since': 'સભ્યપદ:',
      'joined_today': 'આજે જ જોડાયા',
      'days_ago': 'દિવસ પહેલા',
      'days': 'દિવસ',
      'weather_impact': 'હવામાનની અસર',
      'local_forecast_caps': 'સ્થાનિક આગાહી',
      'no_notifications': 'કોઈ નવી સૂચના નથી',
      'crop_vulnerability_caps': 'પાકની સંવેદનશીલતા (તમારી પસંદગી)',
      'no_fav_products_advice': 'હજુ સુધી કોઈ પસંદગીના પાક ઉમેર્યા નથી.\nઉમેરવા માટે મંડી ઇન્ટેલિજન્સ પર જાઓ!',
      'rainfall_probability_caps': 'વરસાદની શક્યતા',
      'expert_advisory_caps': 'નિષ્ણાત સલાહ',
      'loading_advice': 'સલાહ લોડ થઈ રહી છે...',
      'advice_unavailable': 'સલાહ ઉપલબ્ધ નથી',
      'nearby_safe_storage_caps': 'નજીકનું સુરક્ષિત સંગ્રહસ્થાન',
      'govt_warehouse_a1': 'સરકારી ગોદામ A1',
      '2.4_km_away': '2.4 કિમી દૂર',
      'available_space': 'ઉપલબ્ધ જગ્યા',
      'mandi_tools': 'મંડી અને ખેતીના સાધનો',
      'home': 'હોમ',
      'favorites': 'પસંદગીના',
      'what_sown_short': 'તમારા ખેતરમાં શું વાવેલું છે?',
      'nearest_mandi': 'સૌથી નજીકની મંડી',
      'no_products_found': 'નજીકમાં કોઈ પાક મળ્યા નથી',
      'done': 'થઈ ગયું',
      'favorites_alerts': 'પસંદગી અને એલર્ટ',
      'favorite_commodities': 'પસંદગીના પાક',
      'no_favorites_yet': 'હજુ સુધી કોઈ પસંદગી નથી',
      'add_mandis_track': 'સરળતાથી ટ્રેક કરવા માટે મંડીઓ ઉમેરો',
      'active_price_alerts': 'સક્રિય ભાવ એલર્ટ',
      'favorite': 'પસંદગીના',
      'edit_caps': 'ફેરફાર કરો',
      'done_caps': 'થઈ ગયું',
      'skip': 'રદ કરો',
      'search_products': 'શોધો...',
      'price_targets_met': 'ભાવ લક્ષ્યો મળ્યા',
      'no_alerts_set': 'હજુ સુધી કોઈ એલર્ટ નથી',
      'target': 'લક્ષ્ય',
      'hit': 'મળ્યું',
      'stable': 'સ્થિર',
      'set_new_alert': 'નવું એલર્ટ સેટ કરો',
      'set_price_alert': 'ભાવ એલર્ટ સેટ કરો',
      'alert_me_when': 'એલર્ટ આપો જ્યારે ભાવ હોય:',
      'target_price': 'લક્ષ્ય ભાવ',
      'save_alert': 'એલર્ટ સાચવો',
      'above': 'થી વધુ',
      'below': 'થી ઓછું',
      'current_price': 'વર્તમાન ભાવ',
      'live_caps': 'લાઈવ',
      'stable_caps': 'સ્થિર',
      'live_price_caps': 'લાઈવ ભાવ',
      'hit': 'લક્ષ્ય મળ્યું',
      'price_targets_met': 'ભાવ લક્ષ્યાંકો મળ્યા',
      'reached_desired_price': 'તમારી ઈચ્છિત કિંમત સુધી પહોંચી ગયા છે.',
      'favorite_commodities': 'પસંદગીના પાક',
      'active_price_alerts': 'સક્રિય ભાવ એલર્ટ',
      'insight_for_you': 'તમારા માટે ખાસ',
      'volatile_insight_desc': 'બધી મંડીઓમાં શ્રેષ્ઠ ભાવે ખરીદવા માટે એલર્ટ સેટ કરો.',
      'top_price': 'સૌથી વધુ ભાવ',
      'low_price': 'સૌથી ઓછો ભાવ',
      'get_directions': 'રસ્તો બતાવો',
      'updated': 'અપડેટ કરેલ',
      'recently': 'હમણાં જ',
      'var': 'જાત',
      'grd': 'ગ્રેડ',
      'net_profit': 'કુલ નફો',
      'net_saving': 'કુલ બચત',
      'ai_sell_opp': 'AI: વેચવાની શ્રેષ્ઠ તક',
      'ai_buy_opp': 'AI: ખરીદવાની શ્રેષ્ઠ તક',
      'buy_price_caps': 'ખરીદ કિંમત',
      'sell_price_caps': 'વેચાણ કિંમત',
      'your_budget_caps': 'તમારું બજેટ',
      'mandi_price_caps': 'મંડી ભાવ',
      'expense_breakdown': 'ખર્ચની વિગત',
      'commission': 'કમિશન',
      'labor_loading': 'મજૂરી (લોડિંગ)',
      'freight': 'ભાડું',
      'extra': 'વધારાનું',
      'sale': 'વેચાણ',
      'cost': 'કિંમત',
      'exp': 'ખર્ચ',
      'no_mandis_found': 'કોઈ મંડી મળી નથી',
      'no_products_found': 'કોઈ પાક મળ્યા નથી',
      'refresh_data': 'ડેટા તાજો કરો',
      'syncing_data': 'તાજો ડેટા મેળવી રહ્યા છીએ...',
      'fetching_rates': 'બજાર ભાવ શોધી રહ્યા છીએ...',
      'fetching_products': 'પાકની યાદી તૈયાર કરી રહ્યા છીએ...',
      'data_source': 'ડેટા સ્ત્રોત: DATA.GOV.IN',
      'grains': 'અનાજ',
      'vegetables': 'શાકભાજી',
      'fruits': 'ફળો',
      'spices': 'મસાલા',
      'pulses': 'કઠોળ',
      'oilseeds': 'તેલીબિયાં',
      'fibers': 'રેસા',
      'plantation': 'પ્લાન્ટેશન',
      'flowers': 'ફૂલો',
      'others': 'અન્ય',
      'categories': 'શ્રેણીઓ',
      'fetching_location': 'સ્થાન મેળવી રહ્યા છીએ...',
      'search_bharat_products': 'ભારત પ્રોડક્ટ્સ શોધો...',
      'all': 'બધું',
      'fertilizer': 'ખાતર',
      'seeds': 'બીયારણ',
      'atta': 'લોટ',
      'dal': 'દાળ',
      'in_stock': 'સ્ટોકમાં છે',
      'govt_certified': 'સરકારી પ્રમાણિત',
      'add_to_cart': 'કાર્ટમાં ઉમેરો',
      'no_products_available': 'કોઈ પ્રોડક્ટ ઉપલબ્ધ નથી',
      'lowest_price_first': 'ઓછો ભાવ પહેલા',
      'highest_price_first': 'વધારે ભાવ પહેલા',
      'no_mandi_reports': 'આ પાક માટે કોઈ મંડી રિપોર્ટ નથી.',
      'map': 'નકશો',
      'system_initializing': 'સીસ્ટમ ચાલુ થઈ રહી છે...',
      'connecting_to_bharat_network': 'ભારત નેટવર્ક સાથે જોડાણ...',
      'finding_farm_location': 'તમારા ખેતરનું સ્થાન શોધી રહ્યા છીએ...',
      'location_found': 'સ્થાન મળી ગયું.',
      'welcome_exclamation': 'સ્વાગત છે!',
      'preparing_crops': 'પાક તૈયાર કરી રહ્યા છીએ...',
      'ready_exclamation': 'તૈયાર છે!',
      'bharat_flow_ready': 'ભારતફ્લો તૈયાર છે.',
      'mandi_loaded': 'મંડીઓ લોડ થઈ ગઈ...',
      'empowered_kisan_bharat': 'સશક્ત કિસાન · સશક્ત ભારત',
      'live_price': 'લાઇવ ભાવ: ',
      'alert_me_when_price': 'મને જાણ કરો જ્યારે ભાવ:',
      'quintal': 'ક્વિન્ટલ',
      'soil_health': 'જમીનનું આરોગ્ય',
      'bhai_have_card': 'ભાઈ, શું તમારી પાસે સોઈલ હેલ્થ કાર્ડ છે?',
      'scan_report': 'હા, રિપોર્ટ સ્કેન કરો',
      'find_lab': 'ના, નજીકની લેબ શોધો',
      'how_to_sample': 'જમીનનું સેમ્પલ કેવી રીતે લેવું?',
      'nearby_labs': 'નજીકની લેબ્સ',
      'previous_reports': 'અગાઉના રિપોર્ટ્સ',
      'national_level': 'રાષ્ટ્રીય સ્તર',
      'state_level': 'રાજ્ય સ્તર',
      'online': 'ઓનલાઇન',
      'km_away': 'કિમી દૂર',
      'step1': 'ખેતરમાંથી 8-10 જગ્યાએથી માટી લો.',
      'step2': '6 ઇંચ ઊંડો "V" આકારનો ખાડો ખોદો.',
      'step3': 'ઘાસ અને કચરો સાફ કરો.',
      'step4': 'બધું ભેગું કરીને 500 ગ્રામ માટી લેબમાં મોકલો.',
      'buyer_tab': 'ખરીદદાર (Buyer)',
      'seller_tab': 'વિક्रेતા (Seller)',
    },
    'Punjabi': {'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ,', 'farmer': 'ਕਿਸਾਨ', 'trader': 'ਵਪਾਰੀ', 'mandi': 'ਮੰਡੀ ਭਾਅ', 'news': 'ਖ਼ਬਰਾਂ', 'khata': 'ਡਿਜੀਟਲ ਖਾਤਾ', 'mandi_intelligence': 'ਮੰਡੀ ਇੰਟੈਲੀਜੈਂਸ', 'mandis': 'ਮੰਡੀਆਂ', 'products': 'ਫਸਲਾਂ', 'search_products': 'ਫਸਲ ਖੋਜੋ...'},
    'Marathi': {'welcome': 'स्वागत आहे,', 'farmer': 'शेतकरी', 'trader': 'व्यापारी', 'mandi': 'बाजार भाव', 'news': 'बातम्या', 'khata': 'डिजिटल खाते', 'mandi_intelligence': 'मंडी इंटेलिजन्स', 'mandis': 'मंडई', 'products': 'पिके', 'search_products': 'पिके शोधा...'},
    'Bengali': {'welcome': 'স্বাগতম,', 'farmer': 'কৃষক', 'trader': 'ব্যবসায়ী', 'mandi': 'মাণ্ডি দর', 'news': 'খবর', 'khata': 'ডিজিটাল খাতা', 'mandi_intelligence': 'মাণ্ডি ইন্টেলিজেন্স', 'mandis': 'মাণ্ডি', 'products': 'পণ্য', 'search_products': 'পণ্য খুঁজুন...'},
    'Telugu': {'welcome': 'స్వాగతం,', 'farmer': 'రైతు', 'trader': 'వ్యాపారి', 'mandi': 'మండి ధరలు', 'news': 'వార్తలు', 'khata': 'డిజిటల్ ఖాతా', 'mandi_intelligence': 'మండి ఇంటెలిజెన్స్', 'mandis': 'మండీలు', 'products': 'ఉత్పత్తులు', 'search_products': 'ఉత్పత్తుల శోధన...'},
    'Tamil': {'welcome': 'வரவேற்கிறோம்,', 'farmer': 'விவசாயி', 'trader': 'வணிகர்', 'mandi': 'மண்டி விலைகள்', 'news': 'செய்திகள்', 'khata': 'டிஜிட்டல் கணக்கு', 'mandi_intelligence': 'மண்டி நுண்ணறிவு', 'mandis': 'மண்டிகள்', 'products': 'தயারিப்புகள்', 'search_products': 'தயারিப்புகளைத் தேடுங்கள்...'},
    'Kannada': {'welcome': 'ಸ್ವಾಗತ,', 'farmer': 'ರೈತ', 'trader': 'ವ್ಯಾಪಾರಿ', 'mandi': 'ಮಂಡಿ ಬೆಲೆಗಳು', 'news': 'ಸುದ್ದಿಗಳು', 'khata': 'ಡಿಜಿಟಲ್ ಖಾತೆ', 'mandi_intelligence': 'ಮಂಡಿ ಇಂಟೆಲಿಜೆನ್ಸ್', 'mandis': 'ಮಂಡಿಗಳು', 'products': 'ಉತ್ಪನ್ನಗಳು', 'search_products': 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...'},
    'Malayalam': {'welcome': 'സ്വാഗതം,', 'farmer': 'കർഷകൻ', 'trader': 'വ്യാപാരി', 'mandi': 'മണ്ടി വിലകൾ', 'news': 'വാർത്തകൾ', 'khata': 'ഡിജിറ്റൽ ഖാത', 'mandi_intelligence': 'മണ്ടി ഇന്റലിജൻസ്', 'mandis': 'മണ്ടികൾ', 'products': 'ഉൽപ്പന്നങ്ങൾ', 'search_products': 'ഉൽപ്പന്നങ്ങൾ തിരയുക...'},
    'English': {
      'welcome': 'WELCOME BACK,',
      'farmer': 'Farmer',
      'trader': 'Trader',
      'mandi': 'Mandi',
      'product': 'Product',
      'news': 'Market News',
      'khata': 'Digital Khata',
      'mandi_intelligence': 'Mandi Intelligence',
      'search_hint': 'Search Mandis...',
      'mandis': 'MANDIS',
      'products': 'PRODUCTS',
      'search_products': 'Search Products...',
      'home': 'Home',
      'favorites': 'Favorites',
      'soil': 'Soil',
      'logistics': 'Logistics',
      'route': 'Route',
      'subsidy': 'Subsidy',
      'reports': 'Reports',
      'festival': 'Festival',
      'ai_price': 'AI Price',
      'analytics': 'Analytics',
      'trends': 'Trends',
      'govt_buy': 'Govt Buy',
      'offline': 'Offline',
      'compare': 'Compare',
      'voice': 'Voice',
      'mandi_tools': 'Mandi & Farming Tools',
      'items': 'Items',
      'trend_up': 'TREND UP',
      'trend_down': 'TREND DOWN',
      'bharat_munafa_advisor': 'Bharat Munafa Advisor',
      'sell': 'I WANT TO SELL',
      'buy': 'I WANT TO BUY',
      'qty_unit': 'QUANTITY UNIT',
      'search_mandi': 'Search Mandi',
      'source_buy': 'SOURCE (BUY FROM)',
      'target_source': 'TARGET (SOURCE)',
      'select_product': 'SELECT PRODUCT',
      'cost_qty_data': 'COST & QUANTITY DATA',
      'buy_cost': 'BUY COST',
      'budget': 'BUDGET',
      'transport': 'TRANSPORT',
      'extra_cost': 'EXTRA COST',
      'comm_percent': 'COMM (%)',
      'labor_per_q': 'LABOR / Q',
      'sell_analysis': 'SELL ANALYSIS',
      'buy_analysis': 'BUY ANALYSIS',
      'total_cost': 'Total Cost',
      'total_expenses': 'Total Expenses',
      'required_fund': 'REQUIRED FUND',
      'save_analysis': 'Save Analysis',
      'analysis_saved': 'Analysis Saved!',
      'ok': 'OK',
      'explore_all_items': 'Explore All Items',
      'top_movers': 'Top Movers',
      'high_demand': 'High Demand',
      'all_products': 'All Products',
      'distance': 'Distance',
      'timings': 'Timings',
      'phone': 'Phone',
      'call': 'Call',
      'directions': 'Directions',
      'variety_grade': 'VARIETY & GRADE',
      'price_per_qtl': 'PRICE (PER QTL)',
      'grade': 'Grade',
      'range': 'Range',
      'home': 'Home',
      'favorites': 'Favorites',
      'store': 'Store',
      'profile': 'Profile',
      'mandi_tools': 'Mandi & Farming Tools',
      'fetching': 'Fetching...',
      'settings': 'Settings',
      'logout': 'Logout',
      'personal_info': 'Personal Information',
      'language_location': 'Language & Location',
      'auto_language': 'Auto Language',
      'price_alerts': 'Price Alerts',
      'mandi_updates': 'Mandi Updates',
      'security': 'Security',
      'change_pin': 'Change PIN',
      'support': 'Support',
      'net_balance': 'NET BALANCE',
      'total_sales': 'Total Sales',
      'total_expenses': 'Total Expenses',
      'search_transactions': 'Search transactions...',
      'all_transactions': 'All Transactions',
      'recent_activity': 'Recent Activity',
      'add_transaction': 'Add Transaction',
      'title': 'Title',
      'amount': 'Amount',
      'credit': 'Credit',
      'debit': 'Debit',
      'save_transaction': 'SAVE TRANSACTION',
      'live_caps': 'LIVE',
      'stable_caps': 'STABLE',
      'live_price_caps': 'LIVE PRICE',
      'hit': 'HIT',
      'price_targets_met': 'Price Targets Met',
      'reached_desired_price': 'reached your desired prices.',
      'favorite_commodities': 'Favorite Commodities',
      'active_price_alerts': 'Active Price Alerts',
      'insight_for_you': 'INSIGHT FOR YOU',
      'volatile_insight_desc': 'Set alerts to buy at the best price across all mandis.',
      'top_price': 'TOP PRICE',
      'low_price': 'LOW PRICE',
      'get_directions': 'GET DIRECTIONS',
      'updated': 'Updated',
      'recently': 'Recently',
      'var': 'Var',
      'grd': 'Grd',
      'net_profit': 'NET PROFIT',
      'net_saving': 'NET SAVING',
      'ai_sell_opp': 'AI: Best Sell Opportunity',
      'ai_buy_opp': 'AI: Best Buy Opportunity',
      'buy_price_caps': 'BUY PRICE',
      'sell_price_caps': 'SELL PRICE',
      'your_budget_caps': 'YOUR BUDGET',
      'mandi_price_caps': 'MANDI PRICE',
      'expense_breakdown': 'EXPENSE BREAKDOWN',
      'commission': 'Commission',
      'labor_loading': 'Labor (Loading)',
      'freight': 'Freight',
      'extra': 'Extra',
      'sale': 'Sale',
      'cost': 'Cost',
      'exp': 'Exp',
      'no_mandis_found': 'No mandis found',
      'no_products_found': 'No products found',
      'refresh_data': 'Refresh Data',
      'syncing_data': 'Syncing latest market data...',
      'fetching_rates': 'Fetching market rates...',
      'fetching_products': 'Preparing crop list...',
      'data_source': 'Data Source: DATA.GOV.IN',
      'grains': 'Grains',
      'vegetables': 'Vegetables',
      'fruits': 'Fruits',
      'spices': 'Spices',
      'pulses': 'Pulses',
      'oilseeds': 'Oilseeds',
      'fibers': 'Fibers',
      'plantation': 'Plantation',
      'flowers': 'Flowers',
      'others': 'Others',
      'categories': 'Categories',
      'fetching_location': 'Locating...',
      'search_bharat_products': 'Search Bharat products...',
      'buyer_tab': 'Buyer',
      'seller_tab': 'Seller',
      'all': 'All',
      'fertilizer': 'Fertilizer',
      'seeds': 'Seeds',
      'atta': 'Atta',
      'dal': 'Dal',
      'in_stock': 'IN STOCK',
      'govt_certified': 'GOVT CERTIFIED',
      'add_to_cart': 'Add to Cart',
      'no_products_available': 'No products available',
      'lowest_price_first': 'Lowest Price First',
      'highest_price_first': 'Highest Price First',
      'no_mandi_reports': 'No mandi reports for this product yet.',
      'map': 'MAP',
      'system_initializing': 'System Initializing...',
      'connecting_to_bharat_network': 'Connecting to Bharat Network...',
      'finding_farm_location': 'Finding your farm location...',
      'location_found': 'Location Found.',
      'welcome_exclamation': 'Welcome!',
      'preparing_crops': 'Preparing Crops...',
      'ready_exclamation': 'Ready!',
      'bharat_flow_ready': 'BharatFlow is Ready.',
      'mandi_loaded': 'Mandis Loaded...',
      'empowered_kisan_bharat': 'Empowered Kisan · Empowered Bharat',
      'live_price': 'Live Price: ',
      'alert_me_when_price': 'Alert me when price is:',
      'quintal': 'Quintal',
      'soil_health': 'Soil Health',
      'bhai_have_card': 'Do you have a Soil Health Card?',
      'scan_report': 'Yes, Scan Report',
      'find_lab': 'No, Find Nearby Lab',
      'how_to_sample': 'How to collect soil sample?',
      'nearby_labs': 'Nearby Labs',
      'previous_reports': 'Previous Reports',
      'national_level': 'National Level',
      'state_level': 'State Level',
      'online': 'Online',
      'km_away': 'km away',
      'step1': 'Collect soil from 8-10 spots in field.',
      'step2': 'Dig a 6-inch deep "V" shaped hole.',
      'step3': 'Clean grass and debris.',
      'step4': 'Mix all and send 500g soil to lab.',
    },

  };
  
  return data[lang] ?? data['English']!;
});
final mandiTimingsProvider = StateProvider<String>((ref) => '04:00 AM - 08:00 PM');
