import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:bharat_flow/core/utils/language_helper.dart';
import 'package:bharat_flow/core/providers/location_provider.dart';

enum UserRole { farmer, trader, customer }

class AppSettings {
  final UserRole role;
  final String language;
  final bool priceAlerts;
  final bool mandiUpdates;
  final bool pinEnabled;
  final String pinCode;
  final bool autoLanguage;
  final bool weatherNotifications;
  final DateTime? lastSync;

  AppSettings({
    required this.role,
    required this.language,
    required this.priceAlerts,
    required this.mandiUpdates,
    this.pinEnabled = false,
    this.pinCode = '',
    this.autoLanguage = false,
    this.weatherNotifications = true,
    this.lastSync,
  });

  AppSettings copyWith({
    UserRole? role,
    String? language,
    bool? priceAlerts,
    bool? mandiUpdates,
    bool? pinEnabled,
    String? pinCode,
    bool? autoLanguage,
    bool? weatherNotifications,
    DateTime? lastSync,
  }) {
    return AppSettings(
      role: role ?? this.role,
      language: language ?? this.language,
      priceAlerts: priceAlerts ?? this.priceAlerts,
      mandiUpdates: mandiUpdates ?? this.mandiUpdates,
      pinEnabled: pinEnabled ?? this.pinEnabled,
      pinCode: pinCode ?? this.pinCode,
      autoLanguage: autoLanguage ?? this.autoLanguage,
      weatherNotifications: weatherNotifications ?? this.weatherNotifications,
      lastSync: lastSync ?? this.lastSync,
    );
  }
}

class SettingsNotifier extends StateNotifier<AppSettings> {
  final _box = Hive.box('settings');

  SettingsNotifier()
      : super(AppSettings(
          role: UserRole.farmer,
          language: 'English',
          priceAlerts: true,
          mandiUpdates: true,
          autoLanguage: false,
          weatherNotifications: true,
        )) {
    _loadSettings();
  }

  void _loadSettings() {
    final roleIndex = _box.get('role', defaultValue: 0);
    final rawLanguage = _box.get('language', defaultValue: 'English').toString();
    final language = rawLanguage == 'Gujarat' ? 'Gujarati' : rawLanguage;
    final priceAlerts = _box.get('price_alerts', defaultValue: true);
    final mandiUpdates = _box.get('mandi_updates', defaultValue: true);
    final pinEnabled = _box.get('pin_enabled', defaultValue: false);
    final pinCode = _box.get('pin_code', defaultValue: '');
    final autoLanguage = _box.get('auto_language_enabled', defaultValue: false);
    final weatherNotifications =
        _box.get('weather_notifications_enabled', defaultValue: true);
    final lastSyncStr = _box.get('mandi_last_sync');
    final lastSync =
        lastSyncStr != null ? DateTime.tryParse(lastSyncStr.toString()) : null;

    state = AppSettings(
      role: UserRole.values[roleIndex],
      language: language,
      priceAlerts: priceAlerts,
      mandiUpdates: mandiUpdates,
      pinEnabled: pinEnabled,
      pinCode: pinCode,
      autoLanguage: autoLanguage,
      weatherNotifications: weatherNotifications,
      lastSync: lastSync,
    );
  }

  Future<void> updateLastSync(DateTime time) async {
    state = state.copyWith(lastSync: time);
    await _box.put('mandi_last_sync', time.toIso8601String());
  }

  Future<void> setRole(UserRole role) async {
    state = state.copyWith(role: role);
    await _box.put('role', role.index);
  }

  Future<void> setLanguage(String lang) async {
    final String normalized = lang == 'Gujarat' ? 'Gujarati' : lang;
    final bool isAuto = lang == 'Auto';
    
    state = state.copyWith(language: normalized, autoLanguage: isAuto);
    await _box.put('language', normalized);
    await _box.put('auto_language_enabled', isAuto);
  }

  Future<void> togglePriceAlerts(bool value) async {
    state = state.copyWith(priceAlerts: value);
    await _box.put('price_alerts', value);
  }

  Future<void> toggleMandiUpdates(bool value) async {
    state = state.copyWith(mandiUpdates: value);
    await _box.put('mandi_updates', value);
  }

  Future<void> togglePinSecurity(bool value) async {
    state = state.copyWith(pinEnabled: value);
    await _box.put('pin_enabled', value);
  }

  Future<void> setPinCode(String code) async {
    state = state.copyWith(pinCode: code);
    await _box.put('pin_code', code);
  }

  Future<void> toggleAutoLanguage(bool value) async {
    state = state.copyWith(autoLanguage: value);
    await _box.put('auto_language_enabled', value);
  }

  Future<void> toggleWeatherNotifications(bool value) async {
    state = state.copyWith(weatherNotifications: value);
    await _box.put('weather_notifications_enabled', value);
  }
}

final settingsProvider =
    StateNotifierProvider<SettingsNotifier, AppSettings>((ref) {
  return SettingsNotifier();
});

// Translation Map for core UI
final translationsProvider = Provider<Map<String, String>>((ref) {
  final settings = ref.watch(settingsProvider);
  String lang = settings.language;

  if (settings.autoLanguage) {
    final location = ref.watch(locationProvider);
    final autoLangCode =
        LanguageHelper.getLanguageForLocation(location.state, location.city);

    final codeToName = {
      'hi': 'Hindi',
      'gu': 'Gujarati',
      'pa': 'Punjabi',
      'mr': 'Marathi',
      'bn': 'Bengali',
      'te': 'Telugu',
      'ta': 'Tamil',
      'kn': 'Kannada',
      'ml': 'Malayalam'
    };
    lang = codeToName[autoLangCode] ?? 'English';
  }

  final Map<String, Map<String, String>> data = {
    'Hindi': {
      'welcome': 'स्वागत है,',
      'farmer': 'किसान',
      'trader': 'व्यापारी',
      'mandi': 'मंडी',
      'product': 'फसल',
      'news': 'खबरें',
      'khata': 'डिजिटल खाता',
      'store': 'भारत ब्रांड स्टोर',
      'search_hint': 'मंडी खोजें...',
      'closest_mandi': 'नजदीकी मंडी',
      'account': 'खाता',
      'language': 'भाषा',
      'mandi_intelligence': 'मंडी इंटेलिजेंस',
      'mandis': 'मंडियां',
      'products': 'फसलें',
      'search_products': 'फसल खोजें...',
      'home': 'होम',
      'favorites': 'पसंदीदा',
      'soil': 'मिट्टी',
      'logistics': 'लॉजिस्टिक्स',
      'route': 'रास्ता',
      'subsidy': 'सब्सिडी',
      'reports': 'रिपोर्ट',
      'festival': 'त्यौहार',
      'ai_price': 'AI भाव',
      'analytics': 'एनालिटिक्स',
      'trends': 'ट्रेंड्स',
      'govt_buy': 'सरकारी खरीद',
      'offline': 'ऑफलाइन',
      'compare': 'तुलना',
      'voice': 'आवाज',
      'mandi_tools': 'मंडी और खेती के उपकरण',
      'items': 'सामान',
      'trend_up': 'बढ़त',
      'trend_down': 'गिरावट',
      'bharat_munafa_advisor': 'भारत मुनाफा एडवाइजर',
      'sell': 'मैं बेचना चाहता हूँ',
      'buy': 'मैं खरीदना चाहता हूँ',
      'qty_unit': 'मात्रा इकाई',
      'search_mandi': 'मंडी खोजें',
      'source_buy': 'स्रोत (यहाँ से खरीदें)',
      'target_source': 'लक्ष्य (स्रोत)',
      'select_product': 'फसल चुनें',
      'cost_qty_data': 'लागत और मात्रा डेटा',
      'buy_cost': 'खरीद लागत',
      'budget': 'बजट',
      'transport': 'परिवहन',
      'extra_cost': 'अतिरिक्त लागत',
      'comm_percent': 'कमीशन (%)',
      'labor_per_q': 'मजदूरी / क्विंटल',
      'sell_analysis': 'बिक्री विश्लेषण',
      'buy_analysis': 'खरीद विश्लेषण',
      'total_cost': 'कुल लागत',
      'total_expenses': 'कुल खर्च',
      'required_fund': 'आवश्यक फंड',
      'save_analysis': 'विश्लेषण सहेजें',
      'analysis_saved': 'विश्लेषण सहेजा गया!',
      'ok': 'ठीक है',
      'explore_all_items': 'सभी सामान देखें',
      'top_movers': 'आज के टॉप मूवर्स',
      'high_demand': 'अधिक मांग',
      'all_products': 'सभी फसलें',
      'distance': 'दूरी',
      'timings': 'समय',
      'phone': 'फ़ोन',
      'call': 'कॉल करें',
      'directions': 'रास्ता देखें',
      'variety_grade': 'किस्म और ग्रेड',
      'price_per_qtl': 'कीमत (प्रति क्विंटल)',
      'grade': 'ग्रेड',
      'range': 'सीमा',
      'home': 'होम',
      'favorites': 'पसंदीदा',
      'store': 'स्टोर',
      'profile': 'प्रोफ़ाइल',
      'mandi_tools': 'मंडी और खेती के उपकरण',
      'fetching': 'खोज रहे हैं...',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'personal_info': 'व्यक्तिगत जानकारी',
      'account_email': 'अकाउंट ईमेल',
      'mobile_number': 'मोबाइल नंबर',
      'birthday_label': 'जन्म तिथि',
      'city': 'शहर',
      'full_address': 'पूरा पता',
      'app_language': 'ऐप की भाषा',
      'support_help': 'सहायता और मदद',
      'help_center': 'सहायता केंद्र',
      'privacy_policy': 'गोपनीयता नीति',
      'bharatflow_version': 'भारतफ्लो संस्करण',
      'not_set': 'सेट नहीं है',
      'sasta_bazaar': 'सस्ता बाज़ार',
      'digital_khata': 'डिजिटल खाता',
      'community_forum': 'कम्युनिटी फ़ोरम',
      'mera_khet': 'मेरा खेत',
      'view_profile': 'मेरी प्रोफ़ाइल देखें',
      'days_old': 'दिन पुराना',
      'language_location': 'भाषा और स्थान',
      'auto_language': 'स्वचालित भाषा',
      'price_alerts': 'मूल्य अलर्ट',
      'mandi_updates': 'मंडी अपडेट',
      'security': 'सुरक्षा',
      'change_pin': 'पिन बदलें',
      'support': 'सहायता',
      'net_balance': 'कुल शेष',
      'total_sales': 'कुल बिक्री',
      'total_expenses': 'कुल खर्च',
      'search_transactions': 'लेनदेन खोजें...',
      'all_transactions': 'सभी लेनदेन',
      'recent_activity': 'हाल की गतिविधि',
      'add_transaction': 'लेनदेन जोड़ें',
      'title': 'शीर्षक',
      'amount': 'राशि',
      'credit': 'जमा',
      'debit': 'निकासी',
      'save_transaction': 'लेनदेन सहेजें',
      'member_since': 'सदस्यता:',
      'joined_today': 'आज ही जुड़े हैं',
      'days_ago': 'दिन पहले',
      'days': 'दिन',
      'weather_impact': 'मौसम का प्रभाव',
      'local_forecast_caps': 'स्थानीय पूर्वानुमान',
      'no_notifications': 'कोई नई सूचना नहीं है',
      'crop_vulnerability_caps': 'फसल संवेदनशीलता (आपके पसंदीदा)',
      'no_fav_products_advice':
          'अभी तक कोई पसंदीदा फसल नहीं जोड़ी गई है।\nमंडी इंटेलिजेंस में जाकर कुछ जोड़ें!',
      'rainfall_probability_caps': 'बारिश की संभावना',
      'expert_advisory_caps': 'विशेषज्ञ सलाह',
      'loading_advice': 'सलाह लोड हो रही है...',
      'advice_unavailable': 'सलाह उपलब्ध नहीं है',
      'nearby_safe_storage_caps': 'पास के सुरक्षित भंडारण',
      'govt_warehouse_a1': 'सरकारी गोदाम A1',
      '2.4_km_away': '2.4 किमी दूर',
      'available_space': 'उपलब्ध स्थान',
      'mandi_tools': 'मंडी और खेती के उपकरण',
      'home': 'होम',
      'favorites': 'पसंदीदा',
      'what_sown_short': 'आपके खेत में क्या बोया है?',
      'nearest_mandi': 'सबसे पास की मंडी',
      'nearest_warehouses': 'सबसे पास के गोदाम',
      'no_products_found': 'आस-पास कोई फसल नहीं मिली',
      'done': 'हो गया',
      'favorites_alerts': 'पसंदीदा और अलर्ट',
      'favorite_commodities': 'पसंदीदा फसलें',
      'no_favorites_yet': 'अभी तक कोई पसंदीदा नहीं',
      'add_mandis_track': 'आसानी से ट्रैक करने के लिए मंडियाँ जोड़ें',
      'active_price_alerts': 'सक्रिय मूल्य अलर्ट',
      'favorite': 'पसंदीदा',
      'edit_caps': 'बदलें',
      'done_caps': 'हो गया',
      'skip': 'छोड़ें',
      'search_products': 'खोजें...',
      'price_targets_met': 'मूल्य लक्ष्य पूरे हुए',
      'no_alerts_set': 'अभी कोई अलर्ट नहीं है',
      'target': 'लक्ष्य',
      'hit': 'मिल गया',
      'stable': 'स्थिर',
      'set_new_alert': 'नया अलर्ट सेट करें',
      'set_price_alert': 'मूल्य अलर्ट सेट करें',
      'alert_me_when': 'अलर्ट करें जब मूल्य हो:',
      'target_price': 'लक्ष्य मूल्य',
      'save_alert': 'अलर्ट सुरक्षित करें',
      'above': 'ऊपर',
      'below': 'नीचे',
      'current_price': 'वर्तमान मूल्य',
      'live_caps': 'लाइव',
      'stable_caps': 'स्थिर',
      'live_price_caps': 'लाइव मूल्य',
      'hit': 'लक्ष्य मिला',
      'price_targets_met': 'मूल्य लक्ष्य मिले',
      'reached_desired_price': 'आपकी लक्षित कीमत तक पहुँच गया है।',
      'favorite_commodities': 'पसंदीदा फसलें',
      'active_price_alerts': 'सक्रिय मूल्य अलर्ट',
      'insight_for_you': 'आपके लिए जानकारी',
      'volatile_insight_desc':
          'सभी मंडियों में सर्वोत्तम मूल्य पर खरीदने के लिए अलर्ट सेट करें।',
      'top_price': 'उच्चतम भाव',
      'low_price': 'न्यूनतम भाव',
      'get_directions': 'रास्ता देखें',
      'updated': 'अपडेट किया गया',
      'recently': 'अभी हाल ही में',
      'var': 'किस्म',
      'grd': 'ग्रेड',
      'net_profit': 'कुल मुनाफा',
      'net_saving': 'कुल बचत',
      'ai_sell_opp': 'AI: बेचने का सबसे अच्छा अवसर',
      'ai_buy_opp': 'AI: खरीदने का सबसे अच्छा अवसर',
      'buy_price_caps': 'खरीद मूल्य',
      'sell_price_caps': 'बिक्री मूल्य',
      'your_budget_caps': 'आपका बजट',
      'mandi_price_caps': 'मंडी भाव',
      'expense_breakdown': 'खर्चों का विवरण',
      'commission': 'कमीशन',
      'labor_loading': 'मजदूरी (लोडिंग)',
      'freight': 'भाड़ा',
      'extra': 'अतिरिक्त',
      'sale': 'बिक्री',
      'cost': 'लागत',
      'exp': 'खर्च',
      'data_source': 'डेटा स्रोत: DATA.GOV.IN',
      'grains': 'अनाज',
      'vegetables': 'सब्जियाँ',
      'fruits': 'फल',
      'spices': 'मसाले',
      'pulses': 'दालें',
      'oilseeds': 'तिलहन',
      'fibers': 'फाइबर',
      'plantation': 'बागवानी',
      'flowers': 'फूल',
      'others': 'अन्य',
      'categories': 'श्रेणियाँ',
      'fetching_location': 'स्थान खोज रहे हैं...',
      'search_bharat_products': 'भारत उत्पाद खोजें...',
      'all': 'सभी',
      'fertilizer': 'खाद',
      'seeds': 'बीज',
      'atta': 'आटा',
      'dal': 'दाल',
      'in_stock': 'स्टॉक में',
      'govt_certified': 'सरकारी प्रमाणित',
      'add_to_cart': 'कार्ट में जोड़ें',
      'no_products_available': 'कोई उत्पाद उपलब्ध नहीं है',
      'lowest_price_first': 'न्यूनतम भाव पहले',
      'highest_price_first': 'अधिकतम भाव पहले',
      'no_mandi_reports': 'इस उत्पाद के लिए कोई मंडी रिपोर्ट नहीं है।',
      'map': 'नक्शा',
      'system_initializing': 'सीस्टम चालू हो रही है...',
      'connecting_to_bharat_network': 'भारत नेटवर्क के साथ जुड़ाव...',
      'finding_farm_location': 'आपके खेत का स्थान खोज रहे हैं...',
      'location_found': 'स्थान मिल गया।',
      'welcome_exclamation': 'स्वागत है!',
      'preparing_crops': 'फसलें तैयार कर रहे हैं...',
      'ready_exclamation': 'तैयार है!',
      'bharat_flow_ready': 'भारतफ्लो तैयार है।',
      'mandi_loaded': 'मंडियाँ लोड हो गई...',
      'empowered_kisan_bharat': 'सशक्त किसान · सशक्त भारत',
      'live_price': 'लाइव भाव: ',
      'alert_me_when_price': 'मुझे सूचित करें जब भाव:',
      'quintal': 'क्विंटल',
      'soil_health': 'मिट्टी की सेहत',
      'bhai_have_card': 'भाई, क्या आपके पास सॉइल हेल्थ कार्ड है?',
      'scan_report': 'हाँ, रिपोर्ट स्कैन करें',
      'find_lab': 'नहीं, नज़दीकी लैब ढूँढें',
      'how_to_sample': 'मिट्टी का सैंपल कैसे लें?',
      'nearby_labs': 'नज़दीकी लैब',
      'previous_reports': 'पुरानी रिपोर्ट्स',
      'national_level': 'राष्ट्रीय स्तर',
      'state_level': 'राज्य स्तर',
      'online': 'ऑनलाइन',
      'km_away': 'किमी दूर',
      'step1': 'खेत से 8-10 जगह से मिट्टी लें।',
      'step2': '6 इंच गहरा "V" आकार का गड्ढा खोदें।',
      'step3': 'घास और कचरा साफ करें।',
      'step4': 'सबको मिलाकर 500 ग्राम मिट्टी लैब भेजें।',
      'buyer_tab': 'खरीददार (Buyer)',
      'seller_tab': 'विक्रेता (Seller)',
      'munafa_advisor': 'मुनाफा एडवाइजर',
      'warehouse': 'गोदाम (भंडारण)',
      'medicine': 'दवाइयाँ',
      'fuel_price': 'ईंधन भाव',
      'var': 'किस्म',
      'grd': 'ग्रेड',
      'updated': 'अपडेट किया गया',
      'kg': 'किग्रा',
      '20_kg': '20 किग्रा',
      '40_kg': '40 किग्रा',
      'premium_unlock_title': 'प्रीमियम सुविधा अनलॉक करें',
      'unlock': 'अनलॉक करें',
      'cancel': 'रद्द करें',
      'watch_video': 'वीडियो देखें',
      'support_needed': '🌾 आपके सहयोग की आवश्यकता है!',
      'support_desc': 'भारतफ्लो को हमेशा के लिए मुफ्त रखने के लिए, कृपया शेयर करने से पहले २४ घंटे में सिर्फ एक बार यह छोटा वीडियो देखें। हमें उम्मीद है कि आप हमारा समर्थन करेंगे। धन्यवाद!',
      'watch_and_share': '🎬 वीडियो देखें और शेयर करें',
      'cancel_maybe_later': '❌ रद्द करें / बाद में देखें',
      'ad_not_available': 'वीडियो विज्ञापन उपलब्ध नहीं है। सीधी पहुंच प्रदान की गई!',
      'ad_display_failed': 'वीडियो प्रदर्शित नहीं किया जा सका. कृपया पुनः प्रयास करें!',
      'premium_unlock_desc':
          'प्रीमियम फीचर को २४ घंटे के लिए मुफ्त अनलॉक करने के लिए एक छोटा वीडियो देखें। विज्ञापन किसानों के लिए ऐप को मुफ्त रखने में मदद करते हैं। धन्यवाद!',
      'mera_khet_instruction': 'खेत नापने के लिए, मैप पर अपने खेत के चारों कोनों (corners) पर टच करें 👇',
      'backing_up_cloud': 'क्लाउड पर बैकअप लिया जा रहा है...',
      'backup_success': 'बैकअप सफल! ✅',
      'backup_failed': 'बैकअप विफल ❌',
      'restoring_from_cloud': 'क्लाउड से रीस्टोर किया जा रहा है...',
      'restore_success': 'रीस्टोर सफल! ✅',
      'restore_failed': 'रीस्टोर विफल ❌',
      'reports_analysis': 'रिपोर्ट और विश्लेषण',
      'backup_to_cloud': 'क्लाउड पर बैकअप लें',
      'restore_from_cloud': 'क्लाउड से रीस्टोर करें',
      'seven_days': '7 दिन',
      'this_year': 'इस वर्ष',
      'income': 'आय',
      'expense': 'खर्च',
      'cashflow_overview': 'कैशफ्लो विवरण',
      'top_categories': 'शीर्ष श्रेणियां',
      'no_data_available_period': 'इस अवधि के लिए कोई डेटा उपलब्ध नहीं है।',
      'no_transactions_chart': 'चार्ट करने के लिए कोई लेनदेन नहीं है।',
      'clear': 'साफ करें',
      'all_time': 'पूरा समय',
      'today': 'आज',
      'custom_range': 'कस्टम रेंज...',
      'no_transactions_found': 'कोई लेनदेन नहीं मिला।\nनया जोड़ने के लिए + पर टैप करें।',
      'search_mandali': 'मंडली खोजें...',
      'mandalis': 'मण्डलियाँ',
      'error_loading_mandalis': 'मंडली लोड करने में त्रुटि: ',
      'no_cooperatives_found': 'इस क्षेत्र में कोई सहकारी समितियां नहीं मिलीं।',
      'open_now': 'अभी खुला है',
      'closed': 'बंद है',
      'call_center': 'कॉल सेंटर',
      'amazon_promo_text': 'सर्वोत्तम छूट की तलाश है? अमेज़न टुडे डील्स देखें और रोज़मर्रा की ज़रूरी चीज़ों पर बड़ी बचत करें!',
      'amazon_view_deals': 'अमेज़न पर आज के सौदे देखें',
      'camera_take_photo': 'कैमरा से फोटो लें',
      'gallery_choose_photo': 'गैलरी से चुनें',
      'write_question_first': 'कृपया पहले अपना सवाल लिखें!',
      'question_success': 'आपका सवाल सफलतापूर्वक भेजा गया! विशेषज्ञ जल्द ही जवाब देंगे।',
      'failed_to_submit': 'जमा करने में विफल: ',
      'free_expert_advice': 'मुफ्त कृषि विशेषज्ञ सलाह',
      'expert_advice_subtitle': 'फसल बीमारी, खाद या मौसम पर सीधा सवाल पूछें और फोटो भेजें।',
      'choose_category_label': 'विषय चुनें / Choose Category',
      'write_question_detail': 'अपना सवाल विस्तार से लिखें',
      'crop_disease': 'फसल रोग',
      'govt_schemes': 'सरकारी योजनाएं',
      'other_category': 'अन्य',
      'mic_tooltip': 'बोलकर लिखें (Dictate)',
      'agri_direct_help': 'कृषि विशेषज्ञों से सीधी सहायता',
      'attach_crop_photo': 'फसल का फोटो जोड़ें (वैकल्पिक)',
      'upload_photo_prompt': 'कैमरा या गैलरी से फोटो अपलोड करें',
      'photo_clear_hint': 'रोग की सही पहचान के लिए साफ फोटो लें',
      'submitting': 'भेजा जा रहा है...',
      'send_to_expert': 'विशेषज्ञ को सवाल भेजें',
      'no_questions_found': 'कोई सवाल नहीं मिला!',
      'no_questions_subtitle': 'आपने अभी तक कोई सवाल नहीं पूछा है। विशेषज्ञ से सवाल पूछने के लिए पहले टैब पर जाएं।',
      'ask_question_now': 'अभी सवाल पूछें',
      'failed_to_load_questions': 'लोड करने में विफल रहा!',
      'try_again': 'पुनः प्रयास करें',
      'no_qa_found': 'कोई सवाल-जवाब नहीं मिला!',
      'varieties': 'किस्में',
      'grades': 'ग्रेड',
      'market_pulse': 'मार्केट पल्स',
      'average_mandi_price': 'औसत मंडी मूल्य (सभी)',
      'per_quintal': ' /क्विंटल',
      'items_count': 'सामान',
      'sarkari_shop_title': 'सरकारी दुकान (सरकारी दरें)',
      'bhav_for': 'भाव के लिए: ',
      'source': 'स्रोत',
      'updated_today': 'आज अपडेट किया गया',
      'per': 'प्रति',
      'unit': 'इकाई',
      'no_govt_rates_found': 'आपके क्षेत्र के लिए कोई सरकारी दरें नहीं मिलीं',
      'syncing_all_india_db': 'अखिल भारतीय डेटाबेस के साथ सिंक किया जा रहा है...',
      'no_stores_found': 'आस-पास कोई स्टोर नहीं मिला',
      'retry_search': 'पुनः खोजें',
      'govt_approved': 'सरकारी स्वीकृत',
      'open_caps': 'खुला है',
      'closed_caps': 'बंद है',
      'view_on_map': 'नक्शे पर देखें',
      'kisan_pharmacy_title': 'किसान फार्मेसी और उर्वरक स्टोर',
      'farmer_activity': 'किसान गतिविधि:',
      'votes': 'वोट',
      'full_question': 'पूरा है?',
      'yes_word': 'हाँ',
      'no_word': 'नहीं',
      'permanently_closed': 'स्थायी रूप से बंद',
      'farm_insights': 'खेत की जानकारी',
      'weather_tab': 'मौसम',
      'my_farms_tab': 'मेरे खेत',
      'diary_fertilizer_tab': 'डायरी और उर्वरक',
      'current_soil_moisture': 'वर्तमान मिट्टी की नमी',
      'sow_months': 'बुवाई के महीने',
      'crop_cycle': 'फसल चक्र',
      'est_harvest_date': 'अनुमानित फसल तिथि',
      'season': 'मौसम',
      'smart_fertilizer_schedule': 'स्मार्ट उर्वरक अनुसूची',
      'total_requirement_for': 'कुल आवश्यकता के लिए ',
      'sowing_time': 'बुवाई का समय',
      'first_top_dressing': 'पहली टॉप ड्रेसिंग (दिन 20)',
      'second_top_dressing': 'दूसरी टॉप ड्रेसिंग (दिन 45)',
      'apply_npk_dose': 'खाद की खुराक डालें',
      'add_crop_farms_empty': 'उर्वरक कार्यक्रम देखने के लिए मेरे खेत में एक फसल जोड़ें।',
      'based_on_icar_guidelines': 'आईसीएआर दिशानिर्देशों और आपकी बुवाई तिथियों के आधार पर',
      'urea_npk_1st': 'पहली टॉप ड्रेसिंग (यूरिया / एनपीके)',
      'weed_check_2nd': 'खरपतवार नियंत्रण और दूसरा उर्वरक',
      'preventive_pest_spray': 'निवारक कीट स्प्रे',
      'fruit_grain_potash': 'फल/अनाज विकास (पोटाश)',
      'vegetative_growth_desc': 'वानस्पतिक विकास के लिए नाइट्रोजन युक्त उर्वरक डालें।',
      'secondary_nutrients_desc': 'खरपतवार हटाएँ और माध्यमिक पोषक तत्व डालें।',
      'prevent_diseases_desc': 'आम बीमारियों को रोकने के लिए कवकनाशी/कीटनाशक का छिड़काव करें।',
      'boost_grain_desc': 'अनाज का आकार या फल की गुणवत्ता बढ़ाने के लिए पोटेशियम (K) डालें।',
      'farm_area_label': 'खेत का क्षेत्रफल',
      'acres': 'एकड़',
      'bigha': 'बीघा',
      'hectare': 'हेक्टेयर',
      'undo': 'पूर्ववत करें',
      'clear_btn': 'साफ करें',
      'save_crop_map': 'फसल मानचित्र सहेजें',
      'min_3_points_error': 'कृपया खेत बनाने के लिए मानचित्र पर कम से कम 3 बिंदु लगाएं।',
      'select_map_area': 'अगला: मानचित्र क्षेत्र चुनें',
      'mandi_bhav': 'मंडी भाव',
      'mausam': 'मौसम',
      'other': 'अन्य',
      'write_question_hint': 'जैसे: मेरी कपास की फसल में पत्तों पर लाल धब्बे आ रहे हैं, क्या छिड़काव करें?',
      'limit_reached_questions': 'लिमिट पूरी हुई: आप 1 दिन में सिर्फ 3 सवाल पूछ सकते हैं।',
      'no_qa_subtitle': 'इस श्रेणी में वर्तमान में कोई सार्वजनिक प्रश्न उत्तर मौजूद नहीं हैं।',
      'error_loading_forum': 'लोड करने में त्रुटि!',
      'speak_listening': 'बोलिए, हम सुन रहे हैं...',
      'agri_dictation_in_progress': 'कृषि प्रश्न की ऑटो-डिक्टेशन जारी है',
      'starting_to_listen': 'सुनना शुरू हो रहा है...',
      'delete_question_permanently': 'सवाल हमेशा के लिए हटाएं?',
      'delete_question_warning': 'क्या आप इस सवाल को स्थायी रूप से हटाना चाहते हैं? यह क्रिया वापस नहीं ली जा सकती।',
      'delete': 'हटाएं',
      'deleting_question': 'सवाल हटाया जा रहा है...',
      'delete_success': 'सवाल सफलतापूर्वक हटा दिया गया है।',
      'delete_failed': 'हटाने में विफलता! कृपया पुनः प्रयास करें।',
      'status_replied': 'जवाब मिला',
      'status_rejected': 'अस्वीकृत',
      'status_pending': 'लंबित',
      'show_less': 'कम दिखाएं',
      'view_full': 'पूरा देखें',
      'expert_dr_verma': 'डॉ. संजय वर्मा ( Bharat Flow Agri Expert Specialist )',
      'advisory_panel': 'भारतफ्लो कृषि सलाहकार बोर्ड',
      'question_approved_live': 'आपका सवाल स्वीकृत हो गया है और कम्युनिटी फोरम में लाइव है!',
      'advisory_board_rejected': 'कृषि विशेषज्ञ (सलाहकार अस्वीकरण)',
      'rejection_details': 'अस्वीकृति विवरण',
      'query_rejected': 'यह सवाल निरस्त कर दिया गया है।',
      'expert_verifying': 'कृषि विशेषज्ञ आपके सवाल की जांच कर रहे हैं। आपको जल्द ही उत्तर प्राप्त होगा (सामान्यतः 2-4 घंटे में)।',
      'anonymous_kisan': 'गुप्त किसान (निवासी: {city}, {state})',
      'write_answer': 'अपना जवाब लिखें',
      'type_suggestion': 'यहाँ अपना सुझाव टाइप करें...',
      'answer_added': 'जवाब जोड़ा गया!',
      'submit_answer': 'भेजें (Submit)',
      'question_prefix': 'सवाल',
      'expert_verified_answer': 'विशेषज्ञ का जवाब (Expert Response)',
      'community_answers': 'किसानों के सुझाव ({count})',
      'helpful': 'मददगार ({count})',
      'reply': 'जवाब दें',
      'agri_expert_solution': 'भारतफ्लो कृषि विशेषज्ञ समाधान',
      'download_bharatflow': 'इस तरह के और वैज्ञानिक समाधान और मंडी भाव जानने के लिए आज ही BharatFlow App डाउनलोड करें',
      'organic': 'जैविक',
      'processed': 'प्रसंस्कृत',
      'graded': 'श्रेणीबद्ध',
      'packed': 'पैक किया हुआ',
      'ac_storage': 'एसी भंडारण',
      'specs': 'विशेषताएं',
      'description': 'विवरण',
      'additional_info': 'अतिरिक्त जानकारी',
      'seller_name': 'विक्रेता का नाम',
      'quality': 'गुणवत्ता',
      'posted': 'पोस्ट किया',
      'expiry': 'समाप्ति',
      'selling_price': 'अपेक्षित मूल्य',
      'phone_not_available': 'फ़ोन नंबर उपलब्ध नहीं है',
      'cannot_chat': 'चैट नहीं हो सकती: User ID उपलब्ध नहीं',
      'message': 'संदेश',
      'warehouses': 'सत्यापित गोदाम',
      'share': 'शेयर करें',
    },
    'Gujarati': {
      'welcome': 'સ્વાગત છે,',
      'farmer': 'ખેડૂત',
      'trader': 'વેપારી',
      'mandi': 'મંડી',
      'product': 'પાક',
      'news': 'સમાચાર',
      'khata': 'ડિજિટલ ખાતા',
      'store': 'ભારત બ્રાન્ડ સ્ટોર',
      'search_hint': 'મંડી શોધો...',
      'closest_mandi': 'નજીકની મંડી',
      'account': 'ખાતું',
      'language': 'ભાષા',
      'mandi_intelligence': 'મંડી ઇન્ટેલિજન્સ',
      'mandis': 'મંડીઓ',
      'products': 'પાક',
      'search_products': 'પાક શોધો...',
      'home': 'હોમ',
      'favorites': 'પસંદગી',
      'soil': 'જમીન',
      'logistics': 'લોજિસ્ટિક્સ',
      'route': 'રસ્તો',
      'subsidy': 'સબસિડી',
      'reports': 'રિપોર્ટ',
      'festival': 'તહેવાર',
      'ai_price': 'AI ભાવ',
      'analytics': 'એનાલિટિક્સ',
      'trends': 'ટ્રેન્ડ્સ',
      'govt_buy': 'સરકારી ખરીદી',
      'offline': 'ઓફલાઇન',
      'compare': 'તુલના',
      'voice': 'અવાજ',
      'mandi_tools': 'મંડી અને ખેતીના સાધનો',
      'items': 'વસ્તુઓ',
      'trend_up': 'વધારો',
      'trend_down': 'ઘટાડો',
      'bharat_munafa_advisor': 'ભારત મુનાફા એડવાઈઝર',
      'sell': 'મારે વેચવું છે',
      'buy': 'મારે ખરીદવું છે',
      'qty_unit': 'જથ્થાનો એકમ',
      'search_mandi': 'મંડી શોધો',
      'source_buy': 'સ્ત્રોત (અહીંથી ખરીદો)',
      'target_source': 'લક્ષ્ય (સ્ત્રોત)',
      'select_product': 'પાક પસંદ કરો',
      'cost_qty_data': 'ખર્ચ અને જથ્થાનો ડેટા',
      'buy_cost': 'ખરીદ કિંમત',
      'budget': 'બજેટ',
      'transport': 'પરિવહન',
      'extra_cost': 'વધારાનો ખર્ચ',
      'comm_percent': 'કમિશન (%)',
      'labor_per_q': 'મજૂરી / ક્વિન્ટલ',
      'sell_analysis': 'વેચાણ વિશ્લેષણ',
      'buy_analysis': 'ખરીદી વિશ્લેષણ',
      'total_cost': 'કુલ કિંમત',
      'total_expenses': 'કુલ ખર્ચ',
      'required_fund': 'જરૂરી ફંડ',
      'save_analysis': 'વિશ્લેષણ સાચવો',
      'analysis_saved': 'વિશ્લેષણ સાચવવામાં આવ્યું!',
      'ok': 'બરાબર',
      'explore_all_items': 'બધી વસ્તુઓ જુઓ',
      'top_movers': 'આજના ટોચના મૂવર્સ',
      'high_demand': 'વધારે માંગ',
      'all_products': 'બધા પાક',
      'distance': 'અંતર',
      'timings': 'સમય',
      'phone': 'ફોન',
      'call': 'કૉલ કરો',
      'directions': 'દિશાઓ',
      'variety_grade': 'જાત અને ગ્રેડ',
      'price_per_qtl': 'કિંમત (પ્રતિ ક્વિન્ટલ)',
      'grade': 'ગ્રેડ',
      'range': 'રેન્જ',
      'home': 'હોમ',
      'favorites': 'પસંદગીના',
      'store': 'સ્ટોર',
      'profile': 'પ્રોફાઇલ',
      'mandi_tools': 'મંડી અને ખેતીના સાધનો',
      'fetching': 'મેળવી રહ્યા છીએ...',
      'settings': 'સેટિંગ્સ',
      'logout': 'લોગઆઉટ',
      'personal_info': 'વ્યક્તિગત માહિતી',
      'account_email': 'એકાઉન્ટ ઇમેઇલ',
      'mobile_number': 'મોબાઇલ નંબર',
      'birthday_label': 'જન્મ તારીખ',
      'city': 'શહેર',
      'full_address': 'પૂરૂં સરનામું',
      'app_language': 'એપ ભાષા',
      'support_help': 'સપોર્ટ અને મદદ',
      'help_center': 'મદદ કેન્દ્ર',
      'privacy_policy': 'ગોપનીયતા નીતિ',
      'bharatflow_version': 'भारतફ્લો સંસ્કરણ',
      'not_set': 'સેટ નથી',
      'sasta_bazaar': 'સસ્તો બજાર',
      'digital_khata': 'ડિજિટલ ખાતા',
      'community_forum': 'કમ્યુનિટી ફોરમ',
      'mera_khet': 'મારું ખેતર',
      'view_profile': 'મારી પ્રોફાઇલ જુઓ',
      'days_old': 'દિવસ જૂનું',
      'language_location': 'ભાષા અને સ્થાન',
      'auto_language': 'ઓટો લેંગ્વેજ',
      'price_alerts': 'કિંમત એલર્ટ',
      'mandi_updates': 'મંડી અપડેટ્સ',
      'security': 'સુરક્ષા',
      'change_pin': 'પિન બદલો',
      'support': 'સપોર્ટ',
      'net_balance': 'કુલ બેલેન્સ',
      'total_sales': 'કુલ વેચાણ',
      'total_expenses': 'કુલ ખર્ચ',
      'search_transactions': 'લેવડ-દેવડ શોધો...',
      'all_transactions': 'બધી લેવડ-દેવડ',
      'recent_activity': 'તાજેતરની પ્રવૃત્તિ',
      'add_transaction': 'ટ્રાન્ઝેક્શન ઉમેરો',
      'title': 'શીર્ષક',
      'amount': 'રકમ',
      'credit': 'જમા',
      'debit': 'ઉધાર',
      'save_transaction': 'ટ્રાન્ઝેક્શન સાચવો',
      'member_since': 'સભ્યપદ:',
      'joined_today': 'આજે જ જોડાયા',
      'days_ago': 'દિવસ પહેલા',
      'days': 'દિવસ',
      'weather_impact': 'હવામાનની અસર',
      'local_forecast_caps': 'સ્થાનિક આગાહી',
      'no_notifications': 'કોઈ નવી સૂચના નથી',
      'crop_vulnerability_caps': 'પાકની સંવેદનશીલતા (તમારી પસંદગી)',
      'no_fav_products_advice':
          'હજુ સુધી કોઈ પસંદગીના પાક ઉમેર્યા નથી.\nઉમેરવા માટે મંડી ઇન્ટેલિજન્સ પર જાઓ!',
      'rainfall_probability_caps': 'વરસાદની શક્યતા',
      'expert_advisory_caps': 'નિષ્ણાત સલાહ',
      'loading_advice': 'સલાહ લોડ થઈ રહી છે...',
      'advice_unavailable': 'સલાહ ઉપલબ્ધ નથી',
      'nearby_safe_storage_caps': 'નજીકનું સુરક્ષિત સંગ્રહસ્થાન',
      'govt_warehouse_a1': 'સરકારી ગોદામ A1',
      '2.4_km_away': '2.4 કિમી દૂર',
      'available_space': 'ઉપલબ્ધ જગ્યા',
      'mandi_tools': 'મંડી અને ખેતીના સાધનો',
      'home': 'હોમ',
      'favorites': 'પસંદગીના',
      'what_sown_short': 'તમારા ખેતરમાં શું વાવેલું છે?',
      'nearest_mandi': 'સૌથી નજીકની મંડી',
      'nearest_warehouses': 'સૌથી નજીકના ગોદામો',
      'no_products_found': 'નજીકમાં કોઈ પાક મળ્યા નથી',
      'done': 'થઈ ગયું',
      'favorites_alerts': 'પસંદગી અને એલર્ટ',
      'favorite_commodities': 'પસંદગીના પાક',
      'no_favorites_yet': 'હજુ સુધી કોઈ પસંદગી નથી',
      'add_mandis_track': 'સરળતાથી ટ્રેક કરવા માટે મંડીઓ ઉમેરો',
      'active_price_alerts': 'સક્રિય ભાવ એલર્ટ',
      'favorite': 'પસંદગીના',
      'edit_caps': 'ફેરફાર કરો',
      'done_caps': 'થઈ ગયું',
      'skip': 'રદ કરો',
      'search_products': 'શોધો...',
      'price_targets_met': 'ભાવ લક્ષ્યો મળ્યા',
      'no_alerts_set': 'હજુ સુધી કોઈ એલર્ટ નથી',
      'target': 'લક્ષ્ય',
      'hit': 'મળ્યું',
      'stable': 'સ્થિર',
      'set_new_alert': 'નવું એલર્ટ સેટ કરો',
      'set_price_alert': 'ભાવ એલર્ટ સેટ કરો',
      'alert_me_when': 'એલર્ટ આપો જ્યારે ભાવ હોય:',
      'target_price': 'લક્ષ્ય ભાવ',
      'save_alert': 'એલર્ટ સાચવો',
      'above': 'થી વધુ',
      'below': 'થી ઓછું',
      'current_price': 'વર્તમાન ભાવ',
      'live_caps': 'લાઈવ',
      'stable_caps': 'સ્થિર',
      'live_price_caps': 'લાઈવ ભાવ',
      'hit': 'લક્ષ્ય મળ્યું',
      'price_targets_met': 'ભાવ લક્ષ્યાંકો મળ્યા',
      'reached_desired_price': 'તમારી ઈચ્છિત કિંમત સુધી પહોંચી ગયા છે.',
      'favorite_commodities': 'પસંદગીના પાક',
      'active_price_alerts': 'સક્રિય ભાવ એલર્ટ',
      'insight_for_you': 'તમારા માટે ખાસ',
      'volatile_insight_desc':
          'બધી મંડીઓમાં શ્રેષ્ઠ ભાવે ખરીદવા માટે એલર્ટ સેટ કરો.',
      'top_price': 'સૌથી વધુ ભાવ',
      'low_price': 'સૌથી ઓછો ભાવ',
      'get_directions': 'રસ્તો બતાવો',
      'updated': 'અપડેટ કરેલ',
      'recently': 'હમણાં જ',
      'var': 'જાત',
      'grd': 'ગ્રેડ',
      'net_profit': 'કુલ નફો',
      'net_saving': 'કુલ બચત',
      'ai_sell_opp': 'AI: વેચવાની શ્રેષ્ઠ તક',
      'ai_buy_opp': 'AI: ખરીદવાની શ્રેષ્ઠ તક',
      'buy_price_caps': 'ખરીદ કિંમત',
      'sell_price_caps': 'વેચાણ કિંમત',
      'your_budget_caps': 'તમારું બજેટ',
      'mandi_price_caps': 'મંડી ભાવ',
      'expense_breakdown': 'ખર્ચની વિગત',
      'commission': 'કમિશન',
      'labor_loading': 'મજૂરી (લોડિંગ)',
      'freight': 'ભાડું',
      'extra': 'વધારાનું',
      'sale': 'વેચાણ',
      'cost': 'કિંમત',
      'exp': 'ખર્ચ',
      'no_mandis_found': 'કોઈ મંડી મળી નથી',
      'no_products_found': 'કોઈ પાક મળ્યા નથી',
      'refresh_data': 'ડેટા તાજો કરો',
      'syncing_data': 'તાજો ડેટા મેળવી રહ્યા છીએ...',
      'fetching_rates': 'બજાર ભાવ શોધી રહ્યા છીએ...',
      'fetching_products': 'પાકની યાદી તૈયાર કરી રહ્યા છીએ...',
      'data_source': 'ડેટા સ્ત્રોત: DATA.GOV.IN',
      'grains': 'અનાજ',
      'vegetables': 'શાકભાજી',
      'fruits': 'ફળો',
      'spices': 'મસાલા',
      'pulses': 'કઠોળ',
      'oilseeds': 'તેલીબિયાં',
      'fibers': 'રેસા',
      'plantation': 'પ્લાન્ટેશન',
      'flowers': 'ફૂલો',
      'others': 'અન્ય',
      'categories': 'શ્રેણીઓ',
      'fetching_location': 'સ્થાન મેળવી રહ્યા છીએ...',
      'search_bharat_products': 'ભારત પ્રોડક્ટ્સ શોધો...',
      'all': 'બધું',
      'fertilizer': 'ખાતર',
      'seeds': 'બીયારણ',
      'atta': 'લોટ',
      'dal': 'દાળ',
      'in_stock': 'સ્ટોકમાં છે',
      'govt_certified': 'સરકારી પ્રમાણિત',
      'add_to_cart': 'કાર્ટમાં ઉમેરો',
      'no_products_available': 'કોઈ પ્રોડક્ટ ઉપલબ્ધ નથી',
      'lowest_price_first': 'ઓછો ભાવ પહેલા',
      'highest_price_first': 'વધારે ભાવ પહેલા',
      'no_mandi_reports': 'આ પાક માટે કોઈ મંડી રિપોર્ટ નથી.',
      'map': 'નકશો',
      'system_initializing': 'સીસ્ટમ ચાલુ થઈ રહી છે...',
      'connecting_to_bharat_network': 'ભારત નેટવર્ક સાથે જોડાણ...',
      'finding_farm_location': 'તમારા ખેતરનું સ્થાન શોધી રહ્યા છીએ...',
      'location_found': 'સ્થાન મળી ગયું.',
      'welcome_exclamation': 'સ્વાગત છે!',
      'preparing_crops': 'પાક તૈયાર કરી રહ્યા છીએ...',
      'ready_exclamation': 'તૈયાર છે!',
      'bharat_flow_ready': 'ભારતફ્લો તૈયાર છે.',
      'mandi_loaded': 'મંડીઓ લોડ થઈ ગઈ...',
      'empowered_kisan_bharat': 'સશક્ત કિસાન · સશક્ત ભારત',
      'live_price': 'લાઇવ ભાવ: ',
      'alert_me_when_price': 'મને જાણ કરો જ્યારે ભાવ:',
      'quintal': 'ક્વિન્ટલ',
      'soil_health': 'જમીનનું આરોગ્ય',
      'bhai_have_card': 'ભાઈ, શું તમારી પાસે સોઈલ હેલ્થ કાર્ડ છે?',
      'scan_report': 'હા, રિપોર્ટ સ્કેન કરો',
      'find_lab': 'ના, નજીકની લેબ શોધો',
      'how_to_sample': 'જમીનનું સેમ્પલ કેવી રીતે લેવું?',
      'nearby_labs': 'નજીકની લેબ્સ',
      'previous_reports': 'અગાઉના રિપોર્ટ્સ',
      'national_level': 'રાષ્ટ્રીય સ્તર',
      'state_level': 'રાજ્ય સ્તર',
      'online': 'ઓનલાઇન',
      'km_away': 'કિમી દૂર',
      'step1': 'ખેતરમાંથી 8-10 જગ્યાએથી માટી લો.',
      'step2': '6 ઇંચ ઊંડો "V" આકારનો ખાડો ખોદો.',
      'step3': 'ઘાસ અને કચરો સાફ કરો.',
      'step4': 'બધું ભેગું કરીને 500 ગ્રામ માટી લેબમાં મોકલો.',
      'buyer_tab': 'ખરીદદાર (Buyer)',
      'munafa_advisor': 'મુનાફા એડવાઇઝર',
      'warehouse': 'ગોદામ (સંગ્રહ)',
      'medicine': 'દવાઓ',
      'fuel_price': 'બળતણ ભાવ',
      'var': 'જાત',
      'grd': 'ગ્રેડ',
      'updated': 'અપડેટ કરેલ',
      'kg': 'કિગ્રા',
      '20_kg': '20 કિગ્રા',
      '40_kg': '40 કિગ્રા',
      'seller_tab': 'વિક્રેતા (Seller)',
      'premium_unlock_title': 'પ્રીમિયમ ફીચર અનલોક કરો',
      'unlock': 'અનલૉક કરો',
      'cancel': 'રદ કરો',
      'watch_video': 'વિડિયો જુઓ',
      'support_needed': '🌾 તમારા સહકારની જરૂર છે!',
      'support_desc': 'ભારતફ્લોને કાયમ માટે મફત રાખવા માટે, કૃપા કરીને શેર કરતા પહેલા ૨૪ કલાકમાં માત્ર એક વાર આ નાનો વિડીયો જુઓ. અમને આશા છે કે તમે અમને સહકાર આપશો. આભાર!',
      'watch_and_share': '🎬 વિડિયો જુઓ અને શેર કરો',
      'cancel_maybe_later': '❌ રદ કરો / પછી જોઈશું',
      'ad_not_available': 'વિડિયો જાહેરાત ઉપલબ્ધ નથી. સીધી ઍક્સેસ મંજૂર કરવામાં આવી છે!',
      'ad_display_failed': 'વિડિયો પ્રદર્શિત કરી શકાયો નથી. કૃપા કરીને ફરી પ્રયાસ કરો!',
      'premium_unlock_desc':
          'પ્રીમિયમ ફીચરને ૨૪ કલાક મફત અનલોક કરવા માટે એક નાનો વિડીયો જુઓ. જાહેરાતો ખેડૂતો માટે એપ મફત રાખવામાં મદદ કરે છે. આભાર!',
      'mera_khet_instruction': 'ખેતર માપવા માટે, નકશા પર તમારા ખેતરના ચારેય ખૂણા (corners) પર ટચ કરો 👇',
      'backing_up_cloud': 'ક્લાઉડ પર બેકઅપ લેવામાં આવી રહ્યું છે...',
      'backup_success': 'બેકઅપ સફળ! ✅',
      'backup_failed': 'બેકઅપ નિષ્ફળ ❌',
      'restoring_from_cloud': 'ક્લાઉડ પરથી રીસ્ટોર કરવામાં આવી રહ્યું છે...',
      'restore_success': 'રીસ્ટોર સફળ! ✅',
      'restore_failed': 'રીસ્ટોર નિષ્ફળ ❌',
      'reports_analysis': 'રિપોર્ટ અને વિશ્લેષણ',
      'backup_to_cloud': 'ક્લાઉડ પર બેકઅપ લો',
      'restore_from_cloud': 'ક્લાઉડ પરથી રીસ્ટોર કરો',
      'seven_days': '7 દિવસ',
      'this_year': 'આ વર્ષ',
      'income': 'આવક',
      'expense': 'ખર્ચ',
      'cashflow_overview': 'કેશફ્લો વિગતો',
      'top_categories': 'ટોચની શ્રેણીઓ',
      'no_data_available_period': 'આ સમયગાળા માટે કોઈ ડેટા ઉપલબ્ધ નથી.',
      'no_transactions_chart': 'ચાર્ટ કરવા માટે કોઈ લેવડ-દેવડ નથી.',
      'clear': 'સાફ કરો',
      'all_time': 'આખો સમય',
      'today': 'આજે',
      'custom_range': 'કસ્ટમ રેન્જ...',
      'no_transactions_found': 'કોઈ ટ્રાન્ઝેક્શન મળ્યા નથી.\nનવું ઉમેરવા માટે + પર ટેપ કરો.',
      'search_mandali': 'મંડળી શોધો...',
      'mandalis': 'મંડળીઓ',
      'error_loading_mandalis': 'મંડળી લોડ કરવામાં ભૂલ: ',
      'no_cooperatives_found': 'આ વિસ્તારમાં કોઈ સહકારી મંડળીઓ મળી નથી.',
      'open_now': 'હમણાં ખુલ્લું છે',
      'closed': 'બંધ છે',
      'call_center': 'કૉલ સેન્ટર',
      'amazon_promo_text': 'શ્રેષ્ઠ ડિસ્કાઉન્ટ શોધી રહ્યાં છો? એમેઝોન ટુડે ડીલ્સ જુઓ અને રોજિંદી વસ્તુઓ પર મોટી બચત કરો!',
      'amazon_view_deals': 'એમેઝોન પર આજના સોદા જુઓ',
      'camera_take_photo': 'કેમેરાથી ફોટો લો',
      'gallery_choose_photo': 'ગેલેરીમાંથી પસંદ કરો',
      'write_question_first': 'કૃપા કરીને પહેલા તમારો પ્રશ્ન લખો!',
      'question_success': 'તમારો પ્રશ્ન સફળતાપૂર્વક મોકલવામાં આવ્યો છે! નિષ્ણાતો ટૂંક સમયમાં જવાબ આપશે.',
      'failed_to_submit': 'મોકલવામાં નિષ્ફળ: ',
      'free_expert_advice': 'મફત કૃષિ નિષ્ણાત સલાહ',
      'expert_advice_subtitle': 'પાક રોગ, ખાતર કે હવામાન અંગે સીધો પ્રશ્ન પૂછો અને ફોટો મોકલો.',
      'choose_category_label': 'વિષય પસંદ કરો / Choose Category',
      'write_question_detail': 'તમારો પ્રશ્ન વિગતવાર લખો',
      'crop_disease': 'પાક રોગ',
      'govt_schemes': 'સરકારી યોજનાઓ',
      'other_category': 'અન્ય',
      'mic_tooltip': 'બોલીને લખો (Dictate)',
      'agri_direct_help': 'કૃષિ નિષ્ણાતો દ્વારા સીધી સહાય',
      'attach_crop_photo': 'પાકનો ફોટો ઉમેરો (વૈકલ્પિક)',
      'upload_photo_prompt': 'કેમેરા અથવા ગેલેરીમાંથી ફોટો અપલોડ કરો',
      'photo_clear_hint': 'રોગની સચોટ ઓળખ માટે સ્પષ્ટ ફોટો લો',
      'submitting': 'મોકલાઈ રહ્યું છે...',
      'send_to_expert': 'નિષ્ણાતને પ્રશ્ન મોકલો',
      'no_questions_found': 'કોઈ પ્રશ્ન મળ્યો નથી!',
      'no_questions_subtitle': 'તમે હજુ સુધી કોઈ પ્રશ્ન પૂછ્યો નથી. નિષ્ણાતને પૂછવા માટે પહેલા ટેબ પર જાઓ.',
      'ask_question_now': 'હમણાં પ્રશ્ન પૂછો',
      'failed_to_load_questions': 'લોડ કરવામાં નિષ્ફળ!',
      'try_again': 'ફરી પ્રયાસ કરો',
      'no_qa_found': 'કોઈ પ્રશ્ન-જવાબ મળ્યા નથી!',
      'varieties': 'જાતો',
      'grades': 'ગ્રેડ',
      'market_pulse': 'માર્કેટ પલ્સ',
      'average_mandi_price': 'સરેરાશ મંડી ભાવ (તમામ)',
      'per_quintal': ' /ક્વિન્ટલ',
      'items_count': 'વસ્તુઓ',
      'sarkari_shop_title': 'સરકારી દુકાન (સરકારી ભાવો)',
      'bhav_for': 'ભાવ માટે: ',
      'source': 'સ્ત્રોત',
      'updated_today': 'આજે અપડેટ કરેલ',
      'per': 'પ્રતિ',
      'unit': 'એકમ',
      'no_govt_rates_found': 'તમારા વિસ્તાર માટે કોઈ સરકારી ભાવો મળ્યા નથી',
      'syncing_all_india_db': 'અખિલ ભારતીય ડેટાબેઝ સાથે સિંક થઈ રહ્યું છે...',
      'no_stores_found': 'નજીકમાં કોઈ સ્ટોર મળ્યા નથી',
      'retry_search': 'ફરીથી શોધો',
      'govt_approved': 'સરકારી માન્ય',
      'open_caps': 'ખુલ્લું છે',
      'closed_caps': 'બંધ છે',
      'view_on_map': 'નકશા પર જુઓ',
      'kisan_pharmacy_title': 'કિસાન ફાર્મસી અને ખાતર સ્ટોર્સ',
      'farmer_activity': 'ખેડૂત પ્રવૃત્તિ:',
      'votes': 'મતો',
      'full_question': 'ભરેલું છે?',
      'yes_word': 'હા',
      'no_word': 'ના',
      'permanently_closed': 'કાયમી ધોરણે બંધ',
      'farm_insights': 'ખેતરની માહિતી',
      'weather_tab': 'હવામાન',
      'my_farms_tab': 'મારા ખેતરો',
      'diary_fertilizer_tab': 'ડાયરી અને ખાતર',
      'current_soil_moisture': 'જમીનનો વર્તમાન ભેજ',
      'sow_months': 'વાવણીના મહિના',
      'crop_cycle': 'પાક ચક્ર',
      'est_harvest_date': 'અંદાજિત લણણીની તારીખ',
      'season': 'ઋતુ',
      'smart_fertilizer_schedule': 'સ્માર્ટ ખાતર સમયપત્રક',
      'total_requirement_for': 'કુલ જરૂરિયાત માટે ',
      'sowing_time': 'વાવણીનો સમય',
      'first_top_dressing': 'પ્રથમ ટોપ ડ્રેસિંગ (દિવસ ૨૦)',
      'second_top_dressing': 'બીજું ટોપ ડ્રેસિંગ (દિવસ ૪૫)',
      'apply_npk_dose': 'ખાતરનો ડોઝ આપો',
      'add_crop_farms_empty': 'ખાતરનું સમયપત્રક જોવા માટે મારા ખેતરોમાં પાક ઉમેરો.',
      'based_on_icar_guidelines': 'ICAR માર્ગદર્શિકા અને વાવણી તારીખો પર આધારિત',
      'urea_npk_1st': 'પ્રથમ ટોપ ડ્રેસિંગ (યુરિયા / NPK)',
      'weed_check_2nd': 'નીંદણ નિયંત્રણ અને બીજું ખાતર',
      'preventive_pest_spray': 'જંતુનાશક દવાનો છંટકાવ',
      'fruit_grain_potash': 'ફળ/દાણાનો વિકાસ (પોટાશ)',
      'vegetative_growth_desc': 'વનસ્પતિ વિકાસ માટે નાઇટ્રોજનયુક્ત ખાતર આપો.',
      'secondary_nutrients_desc': 'નીંદણ દૂર કરો અને ગૌણ પોષક તત્વો આપો.',
      'prevent_diseases_desc': 'સામાન્ય રોગો રોકવા માટે ફૂગનાશક/જંતુનાશક દવાનો છંટકાવ કરો.',
      'boost_grain_desc': 'દાણાનું કદ અથવા ફળની ગુણવત્તા વધારવા માટે પોટેશિયમ (K) આપો.',
      'farm_area_label': 'ખેતરનું ક્ષેત્રફળ',
      'acres': 'એકર',
      'bigha': 'વીઘા',
      'hectare': 'હેક્ટર',
      'undo': 'પાછું લો',
      'clear_btn': 'સાફ કરો',
      'save_crop_map': 'પાક નકશો સાચવો',
      'min_3_points_error': 'નકશા પર ઓછામાં ઓછા ૩ બિંદુઓ લગાવો.',
      'select_map_area': 'આગળ: નકશાનો વિસ્તાર પસંદ કરો',
      'mandi_bhav': 'બજાર ભાવ',
      'mausam': 'હવામાન',
      'other': 'અન્ય',
      'write_question_hint': 'જેમ કે: મારા કપાસના પાકમાં પાંદડા પર લાલ ડાઘા પડી રહ્યા છે, શું છાંટવું?',
      'limit_reached_questions': 'મર્યાદા પૂરી થઈ: તમે ૧ દિવસમાં માત્ર ૩ પ્રશ્નો પૂછી શકો છો.',
      'no_qa_subtitle': 'આ શ્રેણીમાં હાલમાં કોઈ સાર્વજનિક પ્રશ્ન-ઉત્તર ઉપલબ્ધ નથી.',
      'error_loading_forum': 'ફોરમ લોડ કરવામાં ભૂલ!',
      'speak_listening': 'બોલો, અમે સાંભળી રહ્યા છીએ...',
      'agri_dictation_in_progress': 'કૃષિ પ્રશ્નનું ઓટો-ડિક્ટેશન ચાલુ છે',
      'starting_to_listen': 'સાંભળવાનું શરૂ થઈ રહ્યું છે...',
      'delete_question_permanently': 'પ્રશ્ન કાયમ માટે કાઢી નાખવો?',
      'delete_question_warning': 'શું તમે ખરેખર આ પ્રશ્નને કાયમ માટે કાઢી નાખવા માંગો છો? આ પ્રક્રિયા પાછી મેળવી શકાશે નહીં.',
      'delete': 'કાઢી નાખો',
      'deleting_question': 'પ્રશ્ન કાઢી નાખવામાં આવી રહ્યો છે...',
      'delete_success': 'પ્રશ્ન સફળતાપૂર્વક કાઢી નાખવામાં આવ્યો છે.',
      'delete_failed': 'પ્રશ્ન કાઢી નાખવામાં નિષ્ફળતા! કૃપા કરીને ફરી પ્રયાસ કરો.',
      'status_replied': 'જવાબ મળ્યો',
      'status_rejected': 'અસ્વીકૃત',
      'status_pending': 'બાકી',
      'show_less': 'ઓછું બતાવો',
      'view_full': 'પૂરું જુઓ',
      'expert_dr_verma': 'ડૉ. સંજય વર્મા ( Bharat Flow Agri Expert Specialist )',
      'advisory_panel': 'ભારતફ્લો કૃષિ સલાહકાર બોર્ડ',
      'question_approved_live': 'તમારો પ્રશ્ન મંજૂર થઈ ગયો છે અને સમુદાય ફોરમમાં લાઇવ છે!',
      'advisory_board_rejected': 'કૃષિ સલાહકાર બોર્ડ (ટિકિટ નકારવામાં આવી)',
      'rejection_details': 'અસ્વીકારની વિગતો',
      'query_rejected': 'આ પ્રશ્ન નકારવામાં આવ્યો છે.',
      'expert_verifying': 'કૃષિ નિષ્ણાતો હાલમાં પાકની વિગતો ચકાસી રહ્યા છે. તમને ટૂંક સમયમાં ઉત્તર અને સૂચના પ્રાપ્ત થશે.',
      'anonymous_kisan': 'ગુપ્ત ખેડૂત (રહેવાસી: {city}, {state})',
      'write_answer': 'તમારો જવાબ લખો',
      'type_suggestion': 'અહીં તમારું સૂચન લખો...',
      'answer_added': 'જવાબ ઉમેરાયો!',
      'submit_answer': 'જવાબ સબમિટ કરો',
      'question_prefix': 'પ્રશ્ન',
      'expert_verified_answer': 'નિષ્ણાત દ્વારા ચકાસાયેલ જવાબ',
      'community_answers': 'ખેડૂતોના સૂચનો ({count})',
      'helpful': 'મદદરૂપ ({count})',
      'reply': 'જવાબ આપો',
      'agri_expert_solution': 'ભારતફ્લો કૃષિ નિષ્ણાત ઉકેલ',
      'download_bharatflow': 'વધુ કૃષિ ઉકેલો અને લાઈવ મંડી ભાવો માટે આજે જ ભારતફ્લો એપ ડાઉનલોડ કરો',
      'organic': 'ઓર્ગેનિક',
      'processed': 'પ્રોસેસ કરેલ',
      'graded': 'ગ્રેડ કરેલ',
      'packed': 'પૅક કરેલ',
      'ac_storage': 'AC સ્ટોરેજ',
      'specs': 'વિશેષતાઓ',
      'description': 'વિગત',
      'additional_info': 'વધારાની માહિતી',
      'seller_name': 'વિક્રેતાનું નામ',
      'quality': 'ગુણવત્તા',
      'posted': 'પ્રકાશિત',
      'expiry': 'સમાપ્તિ',
      'selling_price': 'અપેક્ષિત ભાવ',
      'phone_not_available': 'ફોન નંબર ઉપલબ્ધ નથી',
      'cannot_chat': 'ચેટ કરી શકાતી નથી: User ID ઉપલબ્ધ નથી',
      'message': 'સંદેશ',
      'warehouses': 'ચકાસાયેલ ગોદામો',
      'share': 'શેર કરો',
    },
    'Punjabi': {
      'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ,',
      'farmer': 'ਕਿਸਾਨ',
      'trader': 'ਵਪਾਰੀ',
      'mandi': 'ਮੰਡੀ ਭਾਅ',
      'news': 'ਖ਼ਬਰਾਂ',
      'khata': 'ਡਿਜੀਟਲ ਖਾਤਾ',
      'mandi_intelligence': 'ਮੰਡੀ ਇੰਟੈਲੀਜੈਂਸ',
      'mandis': 'ਮੰਡੀਆਂ',
      'products': 'ਫਸਲਾਂ',
      'search_products': 'ਫਸਲ ਖੋਜੋ...'
    },
    'Marathi': {
      'welcome': 'स्वागत आहे,',
      'farmer': 'शेतकरी',
      'trader': 'व्यापारी',
      'mandi': 'बाजार भाव',
      'news': 'बातम्या',
      'khata': 'डिजिटल खाते',
      'mandi_intelligence': 'मंडी इंटेलिजन्स',
      'mandis': 'मंडई',
      'products': 'पिके',
      'search_products': 'पिके शोधा...'
    },
    'Bengali': {
      'welcome': 'স্বাগতম,',
      'farmer': 'কৃষক',
      'trader': 'ব্যবসায়ী',
      'mandi': 'মাণ্ডি দর',
      'news': 'খবর',
      'khata': 'ডিজিটাল খাতা',
      'mandi_intelligence': 'মাণ্ডি ইন্টেলিজেন্স',
      'mandis': 'মাণ্ডি',
      'products': 'পণ্য',
      'search_products': 'পণ্য খুঁজুন...'
    },
    'Telugu': {
      'welcome': 'స్వాగతం,',
      'farmer': 'రైతు',
      'trader': 'వ్యాపారి',
      'mandi': 'మండి ధరలు',
      'news': 'వార్తలు',
      'khata': 'డిజిటల్ ఖాతా',
      'mandi_intelligence': 'మండి ఇంటెలిజెన్స్',
      'mandis': 'మండీలు',
      'products': 'ఉత్పత్తులు',
      'search_products': 'ఉత్పత్తుల శోధన...'
    },
    'Tamil': {
      'welcome': 'வரவேற்கிறோம்,',
      'farmer': 'விவசாயி',
      'trader': 'வணிகர்',
      'mandi': 'மண்டி விலைகள்',
      'news': 'செய்திகள்',
      'khata': 'டிஜிட்டல் கணக்கு',
      'mandi_intelligence': 'மண்டி நுண்ணறிவு',
      'mandis': 'மண்டிகள்',
      'products': 'தயারিப்புகள்',
      'search_products': 'தயারিப்புகளைத் தேடுங்கள்...'
    },
    'Kannada': {
      'welcome': 'ಸ್ವಾಗತ,',
      'farmer': 'ರೈತ',
      'trader': 'ವ್ಯಾಪಾರಿ',
      'mandi': 'ಮಂಡಿ ಬೆಲೆಗಳು',
      'news': 'ಸುದ್ದಿಗಳು',
      'khata': 'ಡಿಜಿಟಲ್ ಖಾತೆ',
      'mandi_intelligence': 'ಮಂಡಿ ಇಂಟೆಲಿಜೆನ್ಸ್',
      'mandis': 'ಮಂಡಿಗಳು',
      'products': 'ಉತ್ಪನ್ನಗಳು',
      'search_products': 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...'
    },
    'Malayalam': {
      'welcome': 'സ്വാഗതം,',
      'farmer': 'കർഷകൻ',
      'trader': 'വ്യാപാരി',
      'mandi': 'മണ്ടി വിലകൾ',
      'news': 'വാർത്തകൾ',
      'khata': 'ഡിജിറ്റൽ ഖാത',
      'mandi_intelligence': 'മണ്ടി ഇന്റലിജൻസ്',
      'mandis': 'മണ്ടികൾ',
      'products': 'ഉൽപ്പന്നങ്ങൾ',
      'search_products': 'ഉൽപ്പന്നങ്ങൾ തിരയുക...'
    },
    'English': {
      'welcome': 'WELCOME BACK,',
      'farmer': 'Farmer',
      'trader': 'Trader',
      'mandi': 'Mandi',
      'product': 'Product',
      'news': 'Market News',
      'khata': 'Digital Khata',
      'mandi_intelligence': 'Mandi Intelligence',
      'search_hint': 'Search Mandis...',
      'mandis': 'MANDIS',
      'products': 'PRODUCTS',
      'mera_khet_instruction': 'To measure your farm, touch the map to mark all corners of your farm 👇',
      'search_products': 'Search Products...',
      'home': 'Home',
      'favorites': 'Favorites',
      'soil': 'Soil',
      'logistics': 'Logistics',
      'route': 'Route',
      'subsidy': 'Subsidy',
      'reports': 'Reports',
      'festival': 'Festival',
      'ai_price': 'AI Price',
      'analytics': 'Analytics',
      'trends': 'Trends',
      'govt_buy': 'Govt Buy',
      'offline': 'Offline',
      'compare': 'Compare',
      'voice': 'Voice',
      'mandi_tools': 'Mandi & Farming Tools',
      'items': 'Items',
      'trend_up': 'TREND UP',
      'trend_down': 'TREND DOWN',
      'bharat_munafa_advisor': 'Bharat Munafa Advisor',
      'sell': 'I WANT TO SELL',
      'buy': 'I WANT TO BUY',
      'qty_unit': 'QUANTITY UNIT',
      'nearest_mandi': 'Nearest Mandi',
      'nearest_warehouses': 'Nearest Warehouses',
      'search_mandi': 'Search Mandi',
      'source_buy': 'SOURCE (BUY FROM)',
      'target_source': 'TARGET (SOURCE)',
      'select_product': 'SELECT PRODUCT',
      'cost_qty_data': 'COST & QUANTITY DATA',
      'buy_cost': 'BUY COST',
      'budget': 'BUDGET',
      'transport': 'TRANSPORT',
      'extra_cost': 'EXTRA COST',
      'comm_percent': 'COMM (%)',
      'labor_per_q': 'LABOR / Q',
      'sell_analysis': 'SELL ANALYSIS',
      'buy_analysis': 'BUY ANALYSIS',
      'total_cost': 'Total Cost',
      'total_expenses': 'Total Expenses',
      'required_fund': 'REQUIRED FUND',
      'save_analysis': 'Save Analysis',
      'analysis_saved': 'Analysis Saved!',
      'ok': 'OK',
      'explore_all_items': 'Explore All Items',
      'top_movers': 'Top Movers',
      'high_demand': 'High Demand',
      'all_products': 'All Products',
      'distance': 'Distance',
      'timings': 'Timings',
      'phone': 'Phone',
      'call': 'Call',
      'directions': 'Directions',
      'variety_grade': 'VARIETY & GRADE',
      'price_per_qtl': 'PRICE (PER QTL)',
      'grade': 'Grade',
      'range': 'Range',
      'home': 'Home',
      'favorites': 'Favorites',
      'store': 'Store',
      'profile': 'Profile',
      'mandi_tools': 'Mandi & Farming Tools',
      'fetching': 'Fetching...',
      'settings': 'Settings',
      'logout': 'Logout',
      'personal_info': 'Personal Information',
      'account_email': 'Account Email',
      'mobile_number': 'Mobile Number',
      'birthday_label': 'Birthdate',
      'city': 'City',
      'full_address': 'Full Address',
      'app_language': 'App Language',
      'support_help': 'Support & Help',
      'help_center': 'Help Center',
      'privacy_policy': 'Privacy Policy',
      'bharatflow_version': 'BharatFlow Version',
      'not_set': 'Not set',
      'sasta_bazaar': 'Sasta Bazaar',
      'digital_khata': 'Digital Khata',
      'community_forum': 'Community Forum',
      'mera_khet': 'My Farm',
      'view_profile': 'View my Profile',
      'days_old': 'Days Old',
      'language_location': 'Language & Location',
      'auto_language': 'Auto Language',
      'price_alerts': 'Price Alerts',
      'mandi_updates': 'Mandi Updates',
      'security': 'Security',
      'change_pin': 'Change PIN',
      'support': 'Support',
      'net_balance': 'NET BALANCE',
      'total_sales': 'Total Sales',
      'total_expenses': 'Total Expenses',
      'search_transactions': 'Search transactions...',
      'all_transactions': 'All Transactions',
      'recent_activity': 'Recent Activity',
      'add_transaction': 'Add Transaction',
      'title': 'Title',
      'amount': 'Amount',
      'credit': 'Credit',
      'debit': 'Debit',
      'save_transaction': 'SAVE TRANSACTION',
      'live_caps': 'LIVE',
      'stable_caps': 'STABLE',
      'live_price_caps': 'LIVE PRICE',
      'hit': 'HIT',
      'price_targets_met': 'Price Targets Met',
      'reached_desired_price': 'reached your desired prices.',
      'favorite_commodities': 'Favorite Commodities',
      'active_price_alerts': 'Active Price Alerts',
      'insight_for_you': 'INSIGHT FOR YOU',
      'volatile_insight_desc':
          'Set alerts to buy at the best price across all mandis.',
      'top_price': 'TOP PRICE',
      'low_price': 'LOW PRICE',
      'get_directions': 'GET DIRECTIONS',
      'updated': 'Updated',
      'recently': 'Recently',
      'var': 'Var',
      'grd': 'Grd',
      'net_profit': 'NET PROFIT',
      'net_saving': 'NET SAVING',
      'ai_sell_opp': 'AI: Best Sell Opportunity',
      'ai_buy_opp': 'AI: Best Buy Opportunity',
      'buy_price_caps': 'BUY PRICE',
      'sell_price_caps': 'SELL PRICE',
      'your_budget_caps': 'YOUR BUDGET',
      'mandi_price_caps': 'MANDI PRICE',
      'expense_breakdown': 'EXPENSE BREAKDOWN',
      'commission': 'Commission',
      'labor_loading': 'Labor (Loading)',
      'freight': 'Freight',
      'extra': 'Extra',
      'sale': 'Sale',
      'cost': 'Cost',
      'exp': 'Exp',
      'no_mandis_found': 'No mandis found',
      'no_products_found': 'No products found',
      'refresh_data': 'Refresh Data',
      'syncing_data': 'Syncing latest market data...',
      'fetching_rates': 'Fetching market rates...',
      'fetching_products': 'Preparing crop list...',
      'data_source': 'Data Source: DATA.GOV.IN',
      'grains': 'Grains',
      'vegetables': 'Vegetables',
      'fruits': 'Fruits',
      'spices': 'Spices',
      'pulses': 'Pulses',
      'oilseeds': 'Oilseeds',
      'fibers': 'Fibers',
      'plantation': 'Plantation',
      'flowers': 'Flowers',
      'others': 'Others',
      'categories': 'Categories',
      'fetching_location': 'Locating...',
      'search_bharat_products': 'Search Bharat products...',
      'buyer_tab': 'Buyer',
      'seller_tab': 'Seller',
      'all': 'All',
      'fertilizer': 'Fertilizer',
      'seeds': 'Seeds',
      'atta': 'Atta',
      'dal': 'Dal',
      'in_stock': 'IN STOCK',
      'govt_certified': 'GOVT CERTIFIED',
      'add_to_cart': 'Add to Cart',
      'no_products_available': 'No products available',
      'lowest_price_first': 'Lowest Price First',
      'highest_price_first': 'Highest Price First',
      'no_mandi_reports': 'No mandi reports for this product yet.',
      'map': 'MAP',
      'system_initializing': 'System Initializing...',
      'connecting_to_bharat_network': 'Connecting to Bharat Network...',
      'finding_farm_location': 'Finding your farm location...',
      'location_found': 'Location Found.',
      'welcome_exclamation': 'Welcome!',
      'preparing_crops': 'Preparing Crops...',
      'ready_exclamation': 'Ready!',
      'bharat_flow_ready': 'BharatFlow is Ready.',
      'mandi_loaded': 'Mandis Loaded...',
      'empowered_kisan_bharat': 'Empowered Kisan · Empowered Bharat',
      'live_price': 'Live Price: ',
      'alert_me_when_price': 'Alert me when price is:',
      'quintal': 'Quintal',
      'soil_health': 'Soil Health',
      'bhai_have_card': 'Do you have a Soil Health Card?',
      'scan_report': 'Yes, Scan Report',
      'find_lab': 'No, Find Nearby Lab',
      'how_to_sample': 'How to collect soil sample?',
      'nearby_labs': 'Nearby Labs',
      'previous_reports': 'Previous Reports',
      'national_level': 'National Level',
      'state_level': 'State Level',
      'online': 'Online',
      'km_away': 'km away',
      'step1': 'Collect soil from 8-10 spots in field.',
      'step2': 'Dig a 6-inch deep "V" shaped hole.',
      'step3': 'Clean grass and debris.',
      'step4': 'Mix all and send 500g soil to lab.',
      'munafa_advisor': 'Munafa Advisor',
      'warehouse': 'Warehouse',
      'medicine': 'Medicine',
      'fuel_price': 'Fuel Price',
      'var': 'Var',
      'grd': 'Grd',
      'updated': 'updated',
      'kg': 'KG',
      '20_kg': '20 KG',
      '40_kg': '40 KG',
      'premium_unlock_title': 'Premium Feature Unlock',
      'unlock': 'Unlock',
      'cancel': 'Cancel',
      'watch_video': 'Watch Video',
      'support_needed': '🌾 Your Support is Needed!',
      'support_desc': 'To keep BharatFlow free forever, please watch this short video just once in 24 hours before sharing. We hope you will support us. Thank you!',
      'watch_and_share': '🎬 Watch Video and Share',
      'cancel_maybe_later': '❌ Cancel / Maybe Later',
      'ad_not_available': 'Video ad not available. Direct access granted!',
      'ad_display_failed': 'Video could not be displayed. Please try again!',
      'premium_unlock_desc':
          'Watch a short video to unlock this premium feature free for 24 hours. Ads keep BharatFlow 100% free for our farmers. Thank you for your support!',
      'backing_up_cloud': 'Backing up to Cloud...',
      'backup_success': 'Backup Successful! ✅',
      'backup_failed': 'Backup Failed ❌',
      'restoring_from_cloud': 'Restoring from Cloud...',
      'restore_success': 'Restore Successful! ✅',
      'restore_failed': 'Restore Failed ❌',
      'reports_analysis': 'Reports & Analysis',
      'backup_to_cloud': 'Backup to Cloud',
      'restore_from_cloud': 'Restore from Cloud',
      'seven_days': '7 Days',
      'this_year': 'This Year',
      'income': 'Income',
      'expense': 'Expense',
      'cashflow_overview': 'Cashflow Overview',
      'top_categories': 'Top Categories',
      'no_data_available_period': 'No data available for this period.',
      'no_transactions_chart': 'No transactions to chart.',
      'clear': 'Clear',
      'all_time': 'All Time',
      'today': 'Today',
      'custom_range': 'Custom Range...',
      'no_transactions_found': 'No transactions found.\nTap + to add a new entry.',
      'search_mandali': 'Search Mandali...',
      'error_loading_mandalis': 'Error loading mandalis: ',
      'no_cooperatives_found': 'No cooperative societies found in this area.',
      'open_now': 'Open Now',
      'closed': 'Closed',
      'call_center': 'Call Center',
      'amazon_promo_text': 'Looking for the best discounts? Check out Amazon Today Deals and save big on everyday essentials!',
      'amazon_view_deals': "View Today's Deals on Amazon",
      'camera_take_photo': 'Take Photo from Camera',
      'gallery_choose_photo': 'Choose from Gallery',
      'write_question_first': 'Please write your question first!',
      'question_success': 'Question submitted successfully! Experts will reply soon.',
      'failed_to_submit': 'Failed to submit: ',
      'free_expert_advice': 'Free Expert Agri Advice',
      'expert_advice_subtitle': 'Ask directly about crop disease, fertilizers, or weather.',
      'choose_category_label': 'Select Category',
      'write_question_detail': 'Write Question in Detail',
      'crop_disease': 'Crop Disease',
      'govt_schemes': 'Govt Schemes',
      'other_category': 'Other',
      'mic_tooltip': 'Voice Dictate',
      'agri_direct_help': 'Agri Experts directly online',
      'attach_crop_photo': 'Attach Crop Photo (Optional)',
      'upload_photo_prompt': 'Upload photo from Camera / Gallery',
      'photo_clear_hint': 'Clear photo helps in accurate diagnosis',
      'submitting': 'Submitting...',
      'send_to_expert': 'Send to Agri Expert',
      'no_questions_found': 'No questions found!',
      'no_questions_subtitle': 'You haven\'t asked any questions yet. Go to the first tab to ask an expert.',
      'ask_question_now': 'Ask Question Now',
      'failed_to_load_questions': 'Failed to load questions!',
      'try_again': 'Try Again',
      'no_qa_found': 'No Q&A found!',
      'varieties': 'Varieties',
      'grades': 'Grades',
      'market_pulse': 'MARKET PULSE',
      'average_mandi_price': 'Average Mandi Price (All)',
      'per_quintal': ' /quintal',
      'items_count': 'items',
      'sarkari_shop_title': 'Sarkari Shop (Govt Rates)',
      'bhav_for': 'Bhav for: ',
      'source': 'Source',
      'updated_today': 'updated Today',
      'per': 'per',
      'unit': 'unit',
      'no_govt_rates_found': 'No govt rates found for your area',
      'syncing_all_india_db': 'Syncing with All India Database...',
      'no_stores_found': 'No stores found nearby',
      'retry_search': 'Retry Search',
      'govt_approved': 'GOVT APPROVED',
      'open_caps': 'OPEN',
      'closed_caps': 'CLOSED',
      'view_on_map': 'VIEW ON MAP',
      'kisan_pharmacy_title': 'Kisan Pharmacy & Fertilizer Stores',
      'farmer_activity': 'Farmer Activity:',
      'votes': 'votes',
      'full_question': 'Full?',
      'yes_word': 'YES',
      'no_word': 'NO',
      'permanently_closed': 'PERMANENTLY CLOSED',
      'farm_insights': 'Farm Insights',
      'weather_tab': 'Weather',
      'my_farms_tab': 'My Farms',
      'diary_fertilizer_tab': 'Diary & Fertilizer',
      'current_soil_moisture': 'Current Soil Moisture',
      'sow_months': 'Sow Months',
      'crop_cycle': 'Crop Cycle',
      'est_harvest_date': 'Est. Harvest Date',
      'season': 'Season',
      'smart_fertilizer_schedule': 'SMART FERTILIZER SCHEDULE',
      'total_requirement_for': 'Total Requirement for ',
      'sowing_time': 'Sowing Time',
      'first_top_dressing': 'First Top Dressing (Day 20)',
      'second_top_dressing': 'Second Top Dressing (Day 45)',
      'apply_npk_dose': 'Apply fertilizer dose',
      'add_crop_farms_empty': 'Add a crop in My Farms to see the fertilizer schedule.',
      'based_on_icar_guidelines': 'Based on ICAR guidelines & your sowing dates',
      'urea_npk_1st': '1st Top Dressing (Urea / NPK)',
      'weed_check_2nd': 'Weed Check & 2nd Fertilizer',
      'preventive_pest_spray': 'Preventive Pest Spray',
      'fruit_grain_potash': 'Fruit/Grain Development (Potash)',
      'vegetative_growth_desc': 'Apply nitrogen-rich fertilizer for vegetative growth.',
      'secondary_nutrients_desc': 'Remove weeds and apply secondary nutrients.',
      'prevent_diseases_desc': 'Spray fungicide/insecticide to prevent common diseases.',
      'boost_grain_desc': 'Apply Potassium (K) to boost grain size or fruit quality.',
      'farm_area_label': 'FARM AREA',
      'acres': 'Acres',
      'bigha': 'Bigha',
      'hectare': 'Hectare',
      'undo': 'Undo',
      'clear_btn': 'Clear',
      'save_crop_map': 'Save Crop Map',
      'min_3_points_error': 'Please mark at least 3 points on the map to create your farm.',
      'select_map_area': 'Next: Select Map Area',
      'mandi_bhav': 'Mandi Bhav',
      'mausam': 'Weather',
      'other': 'Other',
      'write_question_hint': 'e.g. Cotton crop leaves are getting red spots, what to spray?',
      'limit_reached_questions': 'Limit reached: You can only ask 3 questions per day.',
      'no_qa_subtitle': 'No public answered questions exist for this category yet.',
      'error_loading_forum': 'Error Loading Forum!',
      'speak_listening': 'Speak, we are listening...',
      'agri_dictation_in_progress': 'Auto-dictation of agri query in progress',
      'starting_to_listen': 'Starting to listen...',
      'delete_question_permanently': 'Delete Question Permanently?',
      'delete_question_warning': 'Are you sure you want to permanently delete this question? This action cannot be undone.',
      'delete': 'Delete',
      'deleting_question': 'Deleting question...',
      'delete_success': 'Question deleted successfully.',
      'delete_failed': 'Failed to delete question. Please try again.',
      'status_replied': 'Replied',
      'status_rejected': 'Rejected',
      'status_pending': 'Pending',
      'show_less': 'Show Less',
      'view_full': 'View Full',
      'expert_dr_verma': 'Dr. Sanjay Verma ( Bharat Flow Agri Expert Specialist )',
      'advisory_panel': 'BharatFlow Advisory Panel',
      'question_approved_live': 'Your question is approved and live in the community forum!',
      'advisory_board_rejected': 'Agri Advisory Board (Ticket Rejected)',
      'rejection_details': 'Rejection Details',
      'query_rejected': 'This query has been rejected.',
      'expert_verifying': 'Agri Experts are currently verifying crop details. You will receive a notification and answer soon.',
      'anonymous_kisan': 'Anonymous Kisan (from {city}, {state})',
      'write_answer': 'Write your answer',
      'type_suggestion': 'Type your suggestion here...',
      'answer_added': 'Answer added!',
      'submit_answer': 'Submit Answer',
      'question_prefix': 'Question',
      'expert_verified_answer': 'Expert Verified Answer',
      'community_answers': 'Community Answers ({count})',
      'helpful': 'Helpful ({count})',
      'reply': 'Reply',
      'agri_expert_solution': 'BharatFlow Agri Expert Verified Solution',
      'download_bharatflow': 'For more agricultural solutions and live mandi rates, download the BharatFlow App now',
    },
  };

  final location = ref.watch(locationProvider);
  final englishMap = data['English']!;
  final targetMap = Map<String, String>.from(data[lang] ?? {});

  if (lang != 'English') {
    String langCode = 'hi';
    switch (lang) {
      case 'Hindi':
        langCode = 'hi';
        break;
      case 'Gujarati':
        langCode = 'gu';
        break;
      case 'Punjabi':
        langCode = 'pa';
        break;
      case 'Marathi':
        langCode = 'mr';
        break;
      case 'Bengali':
        langCode = 'bn';
        break;
      case 'Telugu':
        langCode = 'te';
        break;
      case 'Tamil':
        langCode = 'ta';
        break;
      case 'Kannada':
        langCode = 'kn';
        break;
      case 'Malayalam':
        langCode = 'ml';
        break;
      default:
        langCode = 'hi';
    }

    final translationBox = Hive.box('translations_cache');

    for (var entry in englishMap.entries) {
      final key = entry.key;
      final englishValue = entry.value;

      if (!targetMap.containsKey(key)) {
        final cacheKey = '${langCode}_$englishValue';
        if (translationBox.containsKey(cacheKey)) {
          targetMap[key] = translationBox.get(cacheKey) ?? englishValue;
        } else {
          targetMap[key] = englishValue;
          LanguageHelper.translate(englishValue, location.state, location.city)
              .then((translated) {
            if (translated != englishValue) {
              Future.microtask(() => ref.invalidateSelf());
            }
          });
        }
      }
    }
  }

  return targetMap.isEmpty ? englishMap : targetMap;
});
final mandiTimingsProvider =
    StateProvider<String>((ref) => '04:00 AM - 08:00 PM');
